{
  "name": "FootDashboardV1_1_",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "fr-FR",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Staging_MatchResults",
        "isHidden": true,
        "lineageTag": "11f07799-6ae1-4912-8f3a-e5f857d8f864",
        "columns": [
          {
            "name": "match_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "match_id",
            "lineageTag": "0123fc0b-0687-41a2-bf1c-a01948667a9e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "matchday",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "matchday",
            "formatString": "0",
            "lineageTag": "789e5c7e-fec8-4e6a-8b8c-51dcbef64ff3",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "home_team",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "home_team",
            "lineageTag": "94d269a2-97b8-421b-a008-d95be8f357eb",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "away_team",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "away_team",
            "lineageTag": "e56ee954-86f5-4027-8603-c13f8145aab4",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "home_score",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "home_score",
            "formatString": "0",
            "lineageTag": "29533645-5b0d-40c4-bffe-f1197b83572a",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "away_score",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "away_score",
            "formatString": "0",
            "lineageTag": "7b96bb5d-2d67-4679-a263-952b2adf1085",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "stadium",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "stadium",
            "lineageTag": "b1fe7001-1030-42c8-8d42-93d849000928",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "referee",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "referee",
            "lineageTag": "238ed101-41be-4749-b961-175adf91345c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "attendance",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "attendance",
            "formatString": "0",
            "lineageTag": "e2ad91b1-934e-479f-a1ad-3c191f901d23",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "match_date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "match_date",
            "formatString": "Long Date",
            "lineageTag": "156a01d7-bb6d-418b-9e17-a6deac1701e2",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "beaeec36-39bd-4931-bbf5-5e6bfb347081",
                "defaultHierarchy": {
                  "table": "LocalDateTable_776675fc-bef2-45d4-a7a0-3b6198fcefb6",
                  "hierarchy": "Hiérarchie de dates"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Staging_MatchResults",
            "mode": "import",
            "queryGroup": "Staging Queries",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\frede\\Downloads\\match_results_2023_2024.csv\"),[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"match_id\", type text}, {\"matchday\", Int64.Type}, {\"match_date\", type text}, {\"home_team\", type text}, {\"away_team\", type text}, {\"home_score\", Int64.Type}, {\"away_score\", Int64.Type}, {\"stadium\", type text}, {\"referee\", type text}, {\"attendance\", Int64.Type}}),",
                "    #\"Espaces supprimés\" = Table.TransformColumns(#\"Type modifié\",{{\"match_date\", Text.Trim, type text}, {\"home_team\", Text.Trim, type text}, {\"away_team\", Text.Trim, type text}, {\"match_id\", Text.Trim, type text}, {\"stadium\", Text.Trim, type text}, {\"referee\", Text.Trim, type text}}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Espaces supprimés\", \"MatchDateFixed\", each let",
                "  raw = Text.Trim(Text.From([match_date])),",
                "  tryIso = try Date.FromText(raw) otherwise null,",
                "  trySlash = if tryIso = null then try Date.FromText(Text.Replace(raw, \"/\", \"-\")) otherwise tryIso else tryIso,",
                "  tryDayMonth = if trySlash = null then try Date.From(DateTime.FromText(raw)) otherwise trySlash else trySlash,",
                "  tryDdMmYyyy = if tryDayMonth = null and Text.Contains(raw, \"/\") then",
                "    let",
                "      parts = Text.Split(raw, \"/\"),",
                "      day = Number.FromText(parts{0}),",
                "      month = Number.FromText(parts{1}),",
                "      year = Number.FromText(parts{2})",
                "    in",
                "      #date(year, month, day)",
                "    else tryDayMonth",
                "in tryDdMmYyyy),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Personnalisée ajoutée\",{{\"MatchDateFixed\", type date}}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Type modifié1\",{\"match_date\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Colonnes supprimées\",{{\"MatchDateFixed\", \"match_date\"}}),",
                "    #\"Type modifié2\" = Table.TransformColumnTypes(#\"Colonnes renommées\",{{\"matchday\", Int64.Type}, {\"home_score\", Int64.Type}, {\"away_score\", Int64.Type}, {\"attendance\", Int64.Type}}),",
                "    #\"Lignes filtrées\" = Table.SelectRows(#\"Type modifié2\", each true),",
                "    #\"Doublons supprimés\" = Table.Distinct(#\"Lignes filtrées\", {\"match_id\"})",
                "in",
                "    #\"Doublons supprimés\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DateTableTemplate_22b22db3-e60d-4caa-9c20-27e16a0a5213",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "33f3e465-a214-4463-b272-0ae79b95d090",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "ff70bce1-0e3b-4c1f-8f2a-1237f5c9d93d",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Année",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "e59c9b9c-b2bd-42a4-b1c7-2469b3e4d9c3",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoMois",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "25e9f684-620e-4924-beb5-02a307e75bc6",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mois",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "NoMois",
            "lineageTag": "201ae60c-bec2-4468-8255-330d9ac7797d",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoTrimestre",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([NoMois] + 2) / 3)",
            "lineageTag": "4a6084d4-c065-4b12-b494-3e61c03e2714",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [NoTrimestre]",
            "sortByColumn": "NoTrimestre",
            "lineageTag": "028a862d-76b3-4f05-9a5b-47756a56e0bb",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Jour",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "bca09a4d-6455-4304-bd98-9b64dba3905e",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_22b22db3-e60d-4caa-9c20-27e16a0a5213",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "lineageTag": "73a0e260-2942-4805-8326-293abcb260d2",
            "levels": [
              {
                "name": "Année",
                "ordinal": 0,
                "column": "Année",
                "lineageTag": "1973c15f-4a60-46c5-908d-4522845f0d52"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "769a2f83-637f-4037-bc0f-f1d6b5752081"
              },
              {
                "name": "Mois",
                "ordinal": 2,
                "column": "Mois",
                "lineageTag": "31513baa-f243-4a32-93bf-b3237b9e9b36"
              },
              {
                "name": "Jour",
                "ordinal": 3,
                "column": "Jour",
                "lineageTag": "7f3bebbc-f77d-4cca-8edc-5961931b68a3"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "LocalDateTable_776675fc-bef2-45d4-a7a0-3b6198fcefb6",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "06452a56-e36a-4ef5-a59e-183fcb01c31f",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "a1d74024-f6dd-4ad9-90d0-3d7065228625",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Année",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "ab0a0223-6d8f-44bf-a5f0-371d2a6ffbe5",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoMois",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "797af169-3e21-4c26-9f79-4170a2a32473",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mois",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "NoMois",
            "lineageTag": "53780d94-3f1c-4ae1-8476-b01282cc5337",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoTrimestre",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([NoMois] + 2) / 3)",
            "lineageTag": "8f92cc07-6810-40e1-a62b-0ef7b3200b45",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [NoTrimestre]",
            "sortByColumn": "NoTrimestre",
            "lineageTag": "40b9bb23-3527-4914-9f66-03245aed0da1",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Jour",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "62dd1ee6-7f98-4099-b850-de85dfe03e04",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_776675fc-bef2-45d4-a7a0-3b6198fcefb6",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Staging_MatchResults'[match_date])), 1, 1), Date(Year(MAX('Staging_MatchResults'[match_date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "lineageTag": "3fb7850a-b113-49a2-9ccd-8f837aee105d",
            "levels": [
              {
                "name": "Année",
                "ordinal": 0,
                "column": "Année",
                "lineageTag": "e75b851b-fb59-4b83-beed-14efce174129"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "e6e9005f-7d97-4abb-8707-d76dba36410f"
              },
              {
                "name": "Mois",
                "ordinal": 2,
                "column": "Mois",
                "lineageTag": "2ed23be0-6c36-453b-9db6-a988b091a3a8"
              },
              {
                "name": "Jour",
                "ordinal": 3,
                "column": "Jour",
                "lineageTag": "e4639c5b-83f1-4c84-b83d-4a048fde8584"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Staging_PlayerStats",
        "isHidden": true,
        "lineageTag": "f067c762-a261-4bca-9394-2d19dc2b51a1",
        "columns": [
          {
            "name": "player_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "player_id",
            "lineageTag": "abca0d6b-b774-42f9-9a26-8f716744b7c3",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "full_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "full_name",
            "lineageTag": "3f8e67c2-4fbb-4289-8a87-8c2036cd9347",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "club",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "club",
            "lineageTag": "13adbf34-a045-4bf7-9529-b83f0ffbff27",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "position",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "position",
            "lineageTag": "e2c8d9a6-17b0-4b36-bf12-049a818be5e5",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "matches_played",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "matches_played",
            "formatString": "0",
            "lineageTag": "b801cd0b-0487-4a4a-932f-c374952ff719",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "starts",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "starts",
            "formatString": "0",
            "lineageTag": "f34fe454-ee06-4479-94b6-2a418062be4d",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "goals",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "goals",
            "formatString": "0",
            "lineageTag": "7e392948-0f73-4376-b5d0-a9b52864e4be",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "minutes_played",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "minutes_played",
            "formatString": "0",
            "lineageTag": "4a6f6cec-631f-4e25-a383-3ab87a92167c",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "assists",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "assists",
            "formatString": "0",
            "lineageTag": "1442ea70-2ce8-420a-a655-adce3316c03a",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "yellow_cards",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "yellow_cards",
            "formatString": "0",
            "lineageTag": "f995da95-bd0a-4c5a-99be-040a4e23ea75",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "red_cards",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "red_cards",
            "formatString": "0",
            "lineageTag": "a0b0b42f-e90d-4bb0-8529-860e613e6c49",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "shots",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "shots",
            "formatString": "0",
            "lineageTag": "0238c89d-d739-4b12-a91e-e05848022b30",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "shots_on_target",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "shots_on_target",
            "formatString": "0",
            "lineageTag": "ab04777b-ff3a-44be-9106-107da0a9008e",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "clean_sheets",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "clean_sheets",
            "formatString": "0",
            "lineageTag": "c195e93b-d5d0-467c-9148-c5284a3ded44",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "saves",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "saves",
            "formatString": "0",
            "lineageTag": "fedbfdc3-386b-41e4-b352-0eabe86c00bd",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "successful_dribbles",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "successful_dribbles",
            "formatString": "0",
            "lineageTag": "741caf1d-e99f-4916-a6c1-7f50027db7c5",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "interceptions",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "interceptions",
            "formatString": "0",
            "lineageTag": "86205a5e-8c2b-4ce6-8449-5dacc369697e",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "successful_tackles",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "successful_tackles",
            "formatString": "0",
            "lineageTag": "ed4943ee-8e4b-4541-97ec-b02132ebfa52",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Staging_PlayerStats",
            "mode": "import",
            "queryGroup": "Staging Queries",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\frede\\Downloads\\player_stats_season.csv\"),[Delimiter=\",\", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"player_id\", type text}, {\"full_name\", type text}, {\"club\", type text}, {\"position\", type text}, {\"matches_played\", Int64.Type}, {\"starts\", Int64.Type}, {\"minutes_played\", type text}, {\"goals\", Int64.Type}, {\"assists\", Int64.Type}, {\"yellow_cards\", Int64.Type}, {\"red_cards\", Int64.Type}, {\"shots\", Int64.Type}, {\"shots_on_target\", Int64.Type}, {\"clean_sheets\", Int64.Type}, {\"saves\", Int64.Type}, {\"successful_dribbles\", Int64.Type}, {\"interceptions\", Int64.Type}, {\"successful_tackles\", Int64.Type}}),",
                "    #\"Espaces supprimés\" = Table.TransformColumns(#\"Type modifié\",{{\"player_id\", Text.Trim, type text}, {\"full_name\", Text.Trim, type text}, {\"club\", Text.Trim, type text}, {\"position\", Text.Trim, type text}, {\"minutes_played\", Text.Trim, type text}}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Espaces supprimés\", \"minutes_played.1\", each if [minutes_played] is number then",
                "  [minutes_played]",
                "else",
                "  Number.FromText(Text.Replace(Text.Trim(Text.From([minutes_played])), \" min\", \"\"))),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Personnalisée ajoutée\",{{\"minutes_played.1\", Int64.Type}}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Type modifié1\",{\"minutes_played\"}),",
                "    #\"Colonnes permutées\" = Table.ReorderColumns(#\"Colonnes supprimées\",{\"player_id\", \"full_name\", \"club\", \"position\", \"matches_played\", \"starts\", \"goals\", \"minutes_played.1\", \"assists\", \"yellow_cards\", \"red_cards\", \"shots\", \"shots_on_target\", \"clean_sheets\", \"saves\", \"successful_dribbles\", \"interceptions\", \"successful_tackles\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Colonnes permutées\",{{\"minutes_played.1\", \"minutes_played\"}}),",
                "    #\"Doublons supprimés\" = Table.Distinct(#\"Colonnes renommées\", {\"player_id\"})",
                "in",
                "    #\"Doublons supprimés\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Staging_Transfers",
        "isHidden": true,
        "lineageTag": "fee7c460-855f-44a5-9896-1182184dee27",
        "columns": [
          {
            "name": "transfer_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "transfer_id",
            "lineageTag": "90f8187e-c298-4550-93c9-a43646835fe5",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "player",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "player",
            "lineageTag": "dd80da00-b0a2-4ae4-aaa3-b2a2575c5f48",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "player_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "player_id",
            "lineageTag": "2878546c-2867-4c3b-b935-4bab6fbbe68e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "departure_club",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "departure_club",
            "lineageTag": "d55b32c8-9298-405e-b8b7-6627063874d7",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "arrival_club",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "arrival_club",
            "lineageTag": "35f9af51-1f01-43f7-8793-33b46ee72b43",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "transfer_type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "transfer_type",
            "lineageTag": "4b2a2a00-6d2f-4028-b113-cd68e20ee28e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "amount_ME",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "amount_ME",
            "lineageTag": "b7b20cf0-7900-4c63-9db7-419373966a13",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "transfer_date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "transfer_date",
            "formatString": "Long Date",
            "lineageTag": "c480c3b8-9a82-4815-bc34-4049f67b9536",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "f8fb8e4a-f9c2-47e6-b542-ac19e0ae60d1",
                "defaultHierarchy": {
                  "table": "LocalDateTable_8fae75e9-dacc-454d-97aa-fd32e596e033",
                  "hierarchy": "Hiérarchie de dates"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "agent",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "agent",
            "lineageTag": "d6034b09-9d99-4f83-926a-5f895662beb1",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Staging_Transfers",
            "mode": "import",
            "queryGroup": "Staging Queries",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\frede\\Downloads\\transfers_2023_2024.txt\"),[Delimiter=\"#(tab)\", Encoding=65001]),",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"transfer_id\", type text}, {\"player\", type text}, {\"player_id\", type text}, {\"departure_club\", type text}, {\"arrival_club\", type text}, {\"transfer_type\", type text}, {\"amount_ME\", type text}, {\"transfer_date\", type date}, {\"agent\", type text}}),",
                "    #\"Doublons supprimés\" = Table.Distinct(#\"Type modifié\", {\"transfer_id\"}),",
                "    #\"Espaces supprimés\" = Table.TransformColumns(#\"Doublons supprimés\",{{\"player\", Text.Trim, type text}, {\"player_id\", Text.Trim, type text}, {\"departure_club\", Text.Trim, type text}, {\"arrival_club\", Text.Trim, type text}, {\"transfer_type\", Text.Trim, type text}, {\"amount_ME\", Text.Trim, type text}, {\"agent\", Text.Trim, type text}}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Espaces supprimés\", \"AmountMEFixed\", each let",
                "  raw = Text.Trim(Text.From([amount_ME])),",
                "  removeMEuro = Text.Replace(raw, \"M€\", \"\"),",
                "  removeSpaceM = Text.Replace(removeMEuro, \" M\", \"\"),",
                "  removeM = Text.Replace(removeSpaceM, \"M\", \"\"),",
                "  removeSpaces = Text.Replace(removeM, \" \", \"\"),",
                "  result = if removeSpaces = \"\" or removeSpaces = null then 0 else Number.FromText(removeSpaces)",
                "in result),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Personnalisée ajoutée\",{{\"AmountMEFixed\", type number}}),",
                "    #\"Colonnes permutées\" = Table.ReorderColumns(#\"Type modifié1\",{\"transfer_id\", \"player\", \"player_id\", \"departure_club\", \"arrival_club\", \"transfer_type\", \"amount_ME\", \"AmountMEFixed\", \"transfer_date\", \"agent\"}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Colonnes permutées\",{\"amount_ME\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Colonnes supprimées\",{{\"AmountMEFixed\", \"amount_ME\"}})",
                "in",
                "    #\"Colonnes renommées\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_8fae75e9-dacc-454d-97aa-fd32e596e033",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "c0c1df2b-0963-4f68-af69-fcccc6771c31",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "fe8cc62d-236f-4f93-9989-9f2bf7d759f7",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Année",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "fab1ea94-c83a-497e-bba3-a24f6c6a95a9",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoMois",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "f64c7326-e053-4de6-9d3e-00c013dfe430",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mois",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "NoMois",
            "lineageTag": "6fc2ed33-4ef9-48e5-817f-eb90339eb9d8",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoTrimestre",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([NoMois] + 2) / 3)",
            "lineageTag": "043dc38a-3788-4d05-ba2c-45247bd99a3d",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [NoTrimestre]",
            "sortByColumn": "NoTrimestre",
            "lineageTag": "79c03594-8b02-45ba-a5cc-7c362bc65598",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Jour",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "903fae85-537b-4700-b4e4-0772fe7624ef",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_8fae75e9-dacc-454d-97aa-fd32e596e033",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Staging_Transfers'[transfer_date])), 1, 1), Date(Year(MAX('Staging_Transfers'[transfer_date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "lineageTag": "b0b7bd8b-0df3-4d59-a2d9-270235bad9ec",
            "levels": [
              {
                "name": "Année",
                "ordinal": 0,
                "column": "Année",
                "lineageTag": "6f1716c2-9071-49f6-a1ff-109d08e820fc"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "08bf589f-977c-487b-ad66-0c998242dbcb"
              },
              {
                "name": "Mois",
                "ordinal": 2,
                "column": "Mois",
                "lineageTag": "3de6f5c3-8857-4b19-80f7-d870bc00e9ab"
              },
              {
                "name": "Jour",
                "ordinal": 3,
                "column": "Jour",
                "lineageTag": "3262d646-7477-4990-b855-e2a12ffea7c9"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Staging_StadiumAttendance",
        "isHidden": true,
        "lineageTag": "a93290a1-a984-44c8-931c-53b24992fd99",
        "columns": [
          {
            "name": "club",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "club",
            "lineageTag": "bb6d2dd7-af16-40e7-8053-330bac50b073",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "matchday",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "matchday",
            "formatString": "0",
            "lineageTag": "b9576d21-be84-4cf5-8b6b-bcb152c76713",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "date",
            "lineageTag": "d4551685-c11f-479b-94b3-1632ef26d9ab",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "opponent",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "opponent",
            "lineageTag": "54b61d89-38e1-4b93-866c-d942ee84bd0d",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "attendance",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "attendance",
            "formatString": "0",
            "lineageTag": "55274a43-7b7a-4f2c-8dc3-5e5027455d88",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "stadium_capacity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "stadium_capacity",
            "formatString": "0",
            "lineageTag": "4a839061-300c-4d39-8fab-805e51cdf885",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "fill_rate",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "fill_rate",
            "lineageTag": "7a47812a-2367-4e4f-ba40-df941c102ec5",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "weather",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "weather",
            "lineageTag": "8eb86cbb-657a-4e9b-91c8-0be81b7962a5",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "temperature_c",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "temperature_c",
            "formatString": "0",
            "lineageTag": "9818f975-901f-439b-9b39-95a05c9f591f",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Staging_StadiumAttendance",
            "mode": "import",
            "queryGroup": "Staging Queries",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\frede\\Downloads\\stadium_attendance.csv\"),[Delimiter=\";\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"club\", type text}, {\"matchday\", Int64.Type}, {\"date\", type text}, {\"opponent\", type text}, {\"attendance\", Int64.Type}, {\"stadium_capacity\", Int64.Type}, {\"fill_rate\", Int64.Type}, {\"weather\", type text}, {\"temperature_c\", Int64.Type}}),",
                "    #\"Espaces supprimés\" = Table.TransformColumns(#\"Type modifié\",{{\"club\", Text.Trim, type text}, {\"date\", Text.Trim, type text}, {\"opponent\", Text.Trim, type text}, {\"weather\", Text.Trim, type text}}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Espaces supprimés\", \"Personnalisé\", each let",
                "  raw = Text.Trim(Text.From([date])),",
                "  tryIso = try Date.FromText(raw) otherwise null,",
                "  trySlash = if tryIso = null then try Date.FromText(Text.Replace(raw, \"/\", \"-\")) otherwise tryIso else tryIso,",
                "  tryDayMonth = if trySlash = null then try Date.From(DateTime.FromText(raw)) otherwise trySlash else trySlash,",
                "  tryDdMmYyyy = if tryDayMonth = null and Text.Contains(raw, \"/\") then",
                "    let",
                "      parts = Text.Split(raw, \"/\"),",
                "      day = Number.FromText(parts{0}),",
                "      month = Number.FromText(parts{1}),",
                "      year = Number.FromText(parts{2})",
                "    in",
                "      #date(year, month, day)",
                "    else tryDayMonth",
                "in tryDdMmYyyy),",
                "    #\"Colonnes permutées\" = Table.ReorderColumns(#\"Personnalisée ajoutée\",{\"club\", \"matchday\", \"date\", \"Personnalisé\", \"opponent\", \"attendance\", \"stadium_capacity\", \"fill_rate\", \"weather\", \"temperature_c\"}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Colonnes permutées\",{\"date\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Colonnes supprimées\",{{\"Personnalisé\", \"date\"}}),",
                "    #\"Personnalisée ajoutée1\" = Table.AddColumn(#\"Colonnes renommées\", \"FillRatePct\", each [fill_rate] / 10),",
                "    #\"Colonnes permutées1\" = Table.ReorderColumns(#\"Personnalisée ajoutée1\",{\"club\", \"matchday\", \"date\", \"opponent\", \"attendance\", \"stadium_capacity\", \"fill_rate\", \"FillRatePct\", \"weather\", \"temperature_c\"}),",
                "    #\"Colonnes supprimées1\" = Table.RemoveColumns(#\"Colonnes permutées1\",{\"fill_rate\"}),",
                "    #\"Colonnes renommées1\" = Table.RenameColumns(#\"Colonnes supprimées1\",{{\"FillRatePct\", \"fill_rate\"}}),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Colonnes renommées1\",{{\"fill_rate\", type number}})",
                "in",
                "    #\"Type modifié1\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Staging_Sanctions",
        "isHidden": true,
        "lineageTag": "771c4e4a-2145-4d24-baac-d71133a3b9ad",
        "columns": [
          {
            "name": "sanction_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "sanction_id",
            "lineageTag": "93f06edd-65cb-4de1-9cbf-a1dba71a5aca",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "player",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "player",
            "lineageTag": "4618657a-ba0c-41be-8f12-5cf2372da89c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "player_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "player_id",
            "lineageTag": "4af3d218-3e18-4171-a639-3e6e521c3bf0",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "club",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "club",
            "lineageTag": "741c382d-ef2a-4281-9658-729905809f14",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sanction_date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "sanction_date",
            "formatString": "Long Date",
            "lineageTag": "af1d7ff5-6833-4184-af03-16c973a5e9cf",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "62954abf-f0a2-47cb-aefa-1529da878527",
                "defaultHierarchy": {
                  "table": "LocalDateTable_0e28b9c3-ae72-4210-a25c-a7fc4c99d2c6",
                  "hierarchy": "Hiérarchie de dates"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "sanction_type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "sanction_type",
            "lineageTag": "e38a6a32-71b8-4446-8351-d9e9c3b335ed",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "reason",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "reason",
            "lineageTag": "ae838cfb-3922-4114-aaf8-8fddff2e1f0a",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "suspension_matches",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "suspension_matches",
            "formatString": "0",
            "lineageTag": "65abd98d-e6b2-45bf-8656-fa1fcb327a53",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "fine_euros",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "fine_euros",
            "formatString": "0",
            "lineageTag": "8c374ceb-3321-403d-817a-ca074a385b03",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Staging_Sanctions",
            "mode": "import",
            "queryGroup": "Staging Queries",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\frede\\Downloads\\disciplinary_sanctions.csv\"),[Delimiter=\",\", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"sanction_id\", type text}, {\"player\", type text}, {\"player_id\", type text}, {\"club\", type text}, {\"sanction_date\", type date}, {\"sanction_type\", type text}, {\"reason\", type text}, {\"suspension_matches\", Int64.Type}, {\"fine_euros\", Int64.Type}}),",
                "    #\"Espaces supprimés\" = Table.TransformColumns(#\"Type modifié\",{{\"sanction_id\", Text.Trim, type text}, {\"player\", Text.Trim, type text}, {\"player_id\", Text.Trim, type text}, {\"club\", Text.Trim, type text}, {\"sanction_type\", Text.Trim, type text}, {\"reason\", Text.Trim, type text}}),",
                "    #\"Doublons supprimés\" = Table.Distinct(#\"Espaces supprimés\", {\"sanction_id\"})",
                "in",
                "    #\"Doublons supprimés\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_0e28b9c3-ae72-4210-a25c-a7fc4c99d2c6",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "35a21466-e702-4463-8acb-eec004500f36",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "7f787cfc-3110-436a-96da-5533cfe456fa",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Année",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "8c8fe2ac-71bf-48ed-a896-ce11d6ddbef4",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoMois",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "8d105430-45c8-4071-baa5-49cd63e94b50",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mois",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "NoMois",
            "lineageTag": "27cf0de8-f65b-4bf3-bfb6-c343e00375a4",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoTrimestre",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([NoMois] + 2) / 3)",
            "lineageTag": "eb005a90-6a32-4e3f-898c-9c161a3f1d87",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [NoTrimestre]",
            "sortByColumn": "NoTrimestre",
            "lineageTag": "5bf8fe03-c508-40a3-a7d5-f8885bd5b0e8",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Jour",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "7fb7706b-9bf3-441d-98bf-5af035e9aa27",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_0e28b9c3-ae72-4210-a25c-a7fc4c99d2c6",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Staging_Sanctions'[sanction_date])), 1, 1), Date(Year(MAX('Staging_Sanctions'[sanction_date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "lineageTag": "21f941d3-ec1d-4885-904c-7804b792e8be",
            "levels": [
              {
                "name": "Année",
                "ordinal": 0,
                "column": "Année",
                "lineageTag": "a0500c74-3f41-4e47-baa8-88830677395e"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "50f90eeb-9888-4213-a8dd-58b191cd1a2b"
              },
              {
                "name": "Mois",
                "ordinal": 2,
                "column": "Mois",
                "lineageTag": "398afdf7-7e11-4600-97dc-25948fbd6a6f"
              },
              {
                "name": "Jour",
                "ordinal": 3,
                "column": "Jour",
                "lineageTag": "0e5d70ee-8358-404e-bc95-3e0969dd5584"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "DimDate",
        "lineageTag": "1299be6d-3d61-4e00-98ef-77e014ca56d6",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "string",
            "sourceColumn": "DateKey",
            "lineageTag": "5034e9aa-d3cd-4aef-95b5-a06cccfc74d2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "51743fa5-8c35-42e0-abef-3b0081a98819",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "b8d13e74-960e-4026-a359-c0a24664741d",
                "defaultHierarchy": {
                  "table": "LocalDateTable_ff75e868-f378-4c68-a7cc-2d390b38a635",
                  "hierarchy": "Hiérarchie de dates"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "74253a68-5738-4696-8da1-e71dbd2931fd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month",
            "formatString": "0",
            "lineageTag": "302fb95c-9e67-4f80-abdb-5aa65c56890f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Day",
            "dataType": "int64",
            "sourceColumn": "Day",
            "formatString": "0",
            "lineageTag": "fe1fbe53-8304-4d14-80b3-7942607c3519",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "  StartDate = #date(2023, 7, 1),",
                "  EndDate = #date(2024, 8, 31),",
                "  Count = Duration.Days(EndDate - StartDate) + 1,",
                "  Dates = List.Dates(StartDate, Count, #duration(1, 0, 0, 0)),",
                "  ToTable = Table.FromList(Dates, Splitter.SplitByNothing(), {\"DateKey\"}, null, ExtraValues.Error),",
                "  AddDate = Table.AddColumn(ToTable, \"Date\", each [DateKey], type date),",
                "  AddYear = Table.AddColumn(AddDate, \"Year\", each Date.Year([DateKey]), Int64.Type),",
                "  AddMonth = Table.AddColumn(AddYear, \"Month\", each Date.Month([DateKey]), Int64.Type),",
                "  AddDay = Table.AddColumn(AddMonth, \"Day\", each Date.Day([DateKey]), Int64.Type)",
                "in AddDay"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_ff75e868-f378-4c68-a7cc-2d390b38a635",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "906e4110-c8ae-48db-9a93-a26ac473b58b",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "e6e2b00c-10a3-478c-bc51-89aa351dc957",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Année",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "f35c33fa-5de0-4843-8f29-7b57c1224b2d",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoMois",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "e69d2cd6-fbe6-44b6-b05b-0a8cd6caf1dd",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mois",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "NoMois",
            "lineageTag": "d4add236-10c8-453e-9e26-3fcd764a8cb8",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoTrimestre",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([NoMois] + 2) / 3)",
            "lineageTag": "8512d060-6e10-430b-952e-20328c39f53a",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [NoTrimestre]",
            "sortByColumn": "NoTrimestre",
            "lineageTag": "006ea9dc-f37e-48d7-aede-66e90593e821",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Jour",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "84752ca2-1a20-4ed2-bc6f-e7c021244b76",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_ff75e868-f378-4c68-a7cc-2d390b38a635",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('DimDate'[Date])), 1, 1), Date(Year(MAX('DimDate'[Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "lineageTag": "71eefac0-0a83-44bf-85f8-7bcddd28e564",
            "levels": [
              {
                "name": "Année",
                "ordinal": 0,
                "column": "Année",
                "lineageTag": "752ee877-20f2-453b-b90e-d58ba709d514"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "3ffbe71e-ceb8-4394-9eab-85516b124dda"
              },
              {
                "name": "Mois",
                "ordinal": 2,
                "column": "Mois",
                "lineageTag": "cd7c7979-e446-4380-919f-6204d5b742d4"
              },
              {
                "name": "Jour",
                "ordinal": 3,
                "column": "Jour",
                "lineageTag": "c1274a10-93f6-45c0-a7b2-8c1cfecece38"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Staging_Clubs",
        "isHidden": true,
        "lineageTag": "7704d33e-2884-4124-8deb-3a5166c802b9",
        "columns": [
          {
            "name": "club_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "club_id",
            "lineageTag": "db6cbfca-db38-43fc-a8f0-0da69e9810d0",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "club_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "club_name",
            "lineageTag": "1a4ad2f7-1a60-4a11-9ed2-2fbfef20cd40",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "city",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "city",
            "lineageTag": "9fce8344-69e2-4086-a01c-b06a613770b9",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "stadium",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "stadium",
            "lineageTag": "42148bf5-1054-4b99-8963-f0158972ee5e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "capacity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "capacity",
            "formatString": "0",
            "lineageTag": "09fe093a-363c-4cc2-bb7e-3c21e337a014",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "founded",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "founded",
            "formatString": "0",
            "lineageTag": "f2754762-cb58-492e-9578-07bc451a7844",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "president",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "president",
            "lineageTag": "d970731a-83f7-41e4-908c-5db7f8600915",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "coach",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "coach",
            "lineageTag": "fb295934-17dc-4bfe-9426-d95f8438a106",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "budget_ME",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "budget_ME",
            "formatString": "0",
            "lineageTag": "1fdea7af-e257-4db3-b80c-36555ad77361",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "colors",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "colors",
            "lineageTag": "5ab8e886-1b67-4b6f-be6e-4088a2f3456b",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Staging_Clubs",
            "mode": "import",
            "queryGroup": "Staging Queries",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\frede\\Downloads\\clubs.xlsx\"), null, true),",
                "    Clubs_Sheet = Source{[Item=\"Clubs\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Clubs_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"club_id\", type text}, {\"club_name\", type text}, {\"city\", type text}, {\"stadium\", type text}, {\"capacity\", Int64.Type}, {\"founded\", Int64.Type}, {\"president\", type text}, {\"coach\", type text}, {\"budget_ME\", Int64.Type}, {\"colors\", type text}}),",
                "    #\"Espaces supprimés\" = Table.TransformColumns(#\"Type modifié\",{{\"club_id\", Text.Trim, type text}, {\"club_name\", Text.Trim, type text}, {\"city\", Text.Trim, type text}, {\"stadium\", Text.Trim, type text}, {\"president\", Text.Trim, type text}, {\"coach\", Text.Trim, type text}, {\"colors\", Text.Trim, type text}})",
                "in",
                "    #\"Espaces supprimés\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Staging_Players",
        "isHidden": true,
        "lineageTag": "221e95d5-dfb2-43e8-b7e8-650078dbcaff",
        "columns": [
          {
            "name": "player_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "player_id",
            "lineageTag": "d5719926-e91a-4d7f-a502-d5bf94421780",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "last_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "last_name",
            "lineageTag": "126bc96e-8417-45ba-a7a7-a4f170c1727f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "first_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "first_name",
            "lineageTag": "2b1c6d11-a7a1-46c1-9d9d-7bd2f3e95e36",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date_of_birth",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "date_of_birth",
            "formatString": "Long Date",
            "lineageTag": "b970a46c-dd6a-41f7-a79a-96ecfcd269a3",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "dc930c6b-4d5b-43c8-8b11-db68b92a1fcd",
                "defaultHierarchy": {
                  "table": "LocalDateTable_9212df2f-31f2-4d4f-99e0-d419183edf8d",
                  "hierarchy": "Hiérarchie de dates"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "nationality",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "nationality",
            "lineageTag": "00b0612d-0eea-42e9-8d53-2c6edfcac2ef",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "club_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "club_id",
            "lineageTag": "0a6ba6b7-23f8-4d92-905d-bfd2e5272882",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "club",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "club",
            "lineageTag": "445df432-bd74-46b0-806f-129c89fb14c5",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "position",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "position",
            "lineageTag": "ec45a058-13a7-4ac9-90b2-2dc64b74ea54",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "jersey_number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jersey_number",
            "formatString": "0",
            "lineageTag": "9fcde327-6b10-443b-9007-ba93c5ca023a",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "height_cm",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "height_cm",
            "formatString": "0",
            "lineageTag": "79f55b1b-cdad-4d69-9129-6c1cef2a8097",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "weight_kg",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "weight_kg",
            "formatString": "0",
            "lineageTag": "7594e356-9cd8-4efc-82c3-938f6cb3db15",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "strong_foot",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "strong_foot",
            "lineageTag": "2bbd9f19-25e1-4e4d-b616-6a4dbcf4429b",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "club_arrival_date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "club_arrival_date",
            "formatString": "Long Date",
            "lineageTag": "c6d1bd59-bd5a-4643-a2a1-36d7d29b914c",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "d136ba81-6080-4432-924c-af11b4e260c8",
                "defaultHierarchy": {
                  "table": "LocalDateTable_a1fae906-93c6-48ae-8a23-4173ec467089",
                  "hierarchy": "Hiérarchie de dates"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "market_value_ME",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "market_value_ME",
            "lineageTag": "3a4a9ab7-049f-4204-b79b-18b2c53cd4d1",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Staging_Players",
            "mode": "import",
            "queryGroup": "Staging Queries",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\frede\\Downloads\\players.xlsx\"), null, true),",
                "    Goalkeepers_Sheet = Source{[Item=\"Goalkeepers\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Goalkeepers_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"player_id\", type text}, {\"last_name\", type text}, {\"first_name\", type text}, {\"date_of_birth\", type date}, {\"nationality\", type text}, {\"club_id\", type text}, {\"club\", type text}, {\"position\", type text}, {\"jersey_number\", Int64.Type}, {\"height_cm\", type any}, {\"weight_kg\", Int64.Type}, {\"strong_foot\", type text}, {\"club_arrival_date\", type date}, {\"market_value_ME\", type number}}),",
                "    #\"Requête ajoutée\" = Table.Combine({#\"Type modifié\", Staging_Field_Players}),",
                "    #\"Doublons supprimés\" = Table.Distinct(#\"Requête ajoutée\", {\"player_id\"}),",
                "    #\"Espaces supprimés\" = Table.TransformColumns(Table.TransformColumnTypes(#\"Doublons supprimés\", {{\"height_cm\", type text}}, \"en-US\"),{{\"player_id\", Text.Trim, type text}, {\"last_name\", Text.Trim, type text}, {\"first_name\", Text.Trim, type text}, {\"nationality\", Text.Trim, type text}, {\"club_id\", Text.Trim, type text}, {\"club\", Text.Trim, type text}, {\"position\", Text.Trim, type text}, {\"strong_foot\", Text.Trim, type text}, {\"height_cm\", Text.Trim, type text}}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Espaces supprimés\", \"Personnalisé\", each Text.Replace(Text.Trim([height_cm]), \"m\", \"\")),",
                "    #\"Colonnes permutées\" = Table.ReorderColumns(#\"Personnalisée ajoutée\",{\"player_id\", \"last_name\", \"first_name\", \"date_of_birth\", \"nationality\", \"club_id\", \"club\", \"position\", \"jersey_number\", \"height_cm\", \"Personnalisé\", \"weight_kg\", \"strong_foot\", \"club_arrival_date\", \"market_value_ME\"}),",
                "    #\"Espaces supprimés1\" = Table.TransformColumns(#\"Colonnes permutées\",{{\"Personnalisé\", Text.Trim, type text}}),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Espaces supprimés1\",{{\"Personnalisé\", Int64.Type}}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Type modifié1\",{\"height_cm\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Colonnes supprimées\",{{\"Personnalisé\", \"height_cm\"}})",
                "in",
                "    #\"Colonnes renommées\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_9212df2f-31f2-4d4f-99e0-d419183edf8d",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "6b434486-003c-4663-9d47-f1bd2d5bfec3",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "41862cfe-abcc-4ec8-89de-8df91647bd91",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Année",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "bc0522eb-baa5-47ec-a281-243a4a0f2b89",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoMois",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "c7c71496-d74c-418e-b716-ec40d37a6524",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mois",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "NoMois",
            "lineageTag": "ba4f98f7-071d-4ee5-84f6-f076c9fc3a21",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoTrimestre",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([NoMois] + 2) / 3)",
            "lineageTag": "3f591d0a-a1da-4736-9574-eddf08100e4d",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [NoTrimestre]",
            "sortByColumn": "NoTrimestre",
            "lineageTag": "403842d0-0b92-4d27-8b1c-40aaf0de03b4",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Jour",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "6bab4cc0-e8b9-48c7-b99f-def9c0ce5ac4",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_9212df2f-31f2-4d4f-99e0-d419183edf8d",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Staging_Players'[date_of_birth])), 1, 1), Date(Year(MAX('Staging_Players'[date_of_birth])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "lineageTag": "987b9a01-b6de-49b8-90df-e0c4c18fcc28",
            "levels": [
              {
                "name": "Année",
                "ordinal": 0,
                "column": "Année",
                "lineageTag": "e0e4277b-3ba5-47d8-9b10-9d4e9f2450eb"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "33d24b53-eb37-435a-9649-86d3dd880a47"
              },
              {
                "name": "Mois",
                "ordinal": 2,
                "column": "Mois",
                "lineageTag": "74b20658-f89a-4d64-91ec-749c8d6f92d0"
              },
              {
                "name": "Jour",
                "ordinal": 3,
                "column": "Jour",
                "lineageTag": "e5fb7cf9-ed91-4ba0-a050-530d13ff696c"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_a1fae906-93c6-48ae-8a23-4173ec467089",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "1f791a84-8d7e-4723-b5a4-9b2a37a2a4a6",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "37034340-f94b-4dc9-99f8-2f60255256c8",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Année",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "1bdec63e-2708-4379-8a3c-7a57d7d876c0",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoMois",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "07c6d3c9-9bb0-4019-ad62-e3c5daa86eef",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mois",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "NoMois",
            "lineageTag": "a1577f9d-c771-4dfa-a3e0-e4ba2283761f",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoTrimestre",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([NoMois] + 2) / 3)",
            "lineageTag": "adc16288-1daf-4f27-824d-81fff23626e2",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [NoTrimestre]",
            "sortByColumn": "NoTrimestre",
            "lineageTag": "66e9423f-44da-4e5a-9f36-5d890feb73c2",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Jour",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "110166c0-51f0-4989-a87a-2b0c53862ecf",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_a1fae906-93c6-48ae-8a23-4173ec467089",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Staging_Players'[club_arrival_date])), 1, 1), Date(Year(MAX('Staging_Players'[club_arrival_date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "lineageTag": "45933882-5ecb-4ac2-8c6f-1ed80409b4f6",
            "levels": [
              {
                "name": "Année",
                "ordinal": 0,
                "column": "Année",
                "lineageTag": "d959f453-57f6-45db-8f5b-f1f06e88acc8"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "b910b795-ebde-427d-b6d7-f477b5da5f5f"
              },
              {
                "name": "Mois",
                "ordinal": 2,
                "column": "Mois",
                "lineageTag": "e83b3694-87b1-413a-802e-73709c82dfc0"
              },
              {
                "name": "Jour",
                "ordinal": 3,
                "column": "Jour",
                "lineageTag": "9104a9be-7d11-4c72-b67d-03eb3b8858cf"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "DimClub",
        "lineageTag": "da87ef21-61dd-47e4-901b-8e43d5f91ea3",
        "columns": [
          {
            "name": "club_id",
            "dataType": "string",
            "sourceColumn": "club_id",
            "lineageTag": "a8f70848-e811-4e98-8c0c-738c3e63fb3f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ClubName",
            "dataType": "string",
            "sourceColumn": "ClubName",
            "lineageTag": "de8b9849-400d-4832-a97d-d8a077b8d535",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city",
            "lineageTag": "6730e66b-86b3-4436-9401-21fc4f3be86c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "stadium",
            "dataType": "string",
            "sourceColumn": "stadium",
            "lineageTag": "bc7b8e43-fbee-49c8-910f-cd247d4b17ce",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "capacity",
            "dataType": "string",
            "sourceColumn": "capacity",
            "lineageTag": "1537f811-8376-4646-9b8a-81b102e327d0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "founded",
            "dataType": "string",
            "sourceColumn": "founded",
            "lineageTag": "55d6f544-9317-4094-848a-21cf312e6565",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "president",
            "dataType": "string",
            "sourceColumn": "president",
            "lineageTag": "4e725ad1-f91a-489b-ba21-84c28975bf3d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "coach",
            "dataType": "string",
            "sourceColumn": "coach",
            "lineageTag": "d89b4ae4-84f3-4f63-8197-14889c6d78f9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "budget_ME",
            "dataType": "string",
            "sourceColumn": "budget_ME",
            "lineageTag": "91eed2b5-646a-4fbd-ba39-29cf0505d6b3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "colors",
            "dataType": "string",
            "sourceColumn": "colors",
            "lineageTag": "cc5422ea-97a8-491c-a86b-f657380c9246",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ClubKey",
            "dataType": "int64",
            "sourceColumn": "ClubKey",
            "formatString": "0",
            "lineageTag": "9d78f224-6ff5-4506-8f11-9b461ddc9a0e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "External",
            "dataType": "boolean",
            "sourceColumn": "External",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d31a1b31-0b22-44bc-9eab-01ba032f20f8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Club_URL",
            "dataType": "string",
            "sourceColumn": "Club_URL",
            "lineageTag": "7e134993-8f57-4238-a518-e78f4eec9003",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimClub",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // 1. Ligue 1 clubs from Staging_Clubs (your logic + External = false)",
                "    Source = Staging_Clubs,",
                "    AddedIndex = Table.AddIndexColumn(Source, \"ClubKey\", 0, 1, Int64.Type),",
                "    Reordered = Table.ReorderColumns(AddedIndex, {\"ClubKey\", \"club_id\", \"club_name\", \"city\", \"stadium\", \"capacity\", \"founded\", \"president\", \"coach\", \"budget_ME\", \"colors\"}),",
                "    RenamedClubName = Table.RenameColumns(Reordered, {{\"club_name\", \"ClubName\"}}),",
                "    DistinctClubId = Table.Distinct(RenamedClubName, {\"club_id\"}),",
                "    Ligue1Clubs = Table.AddColumn(DistinctClubId, \"External\", each false, type logical),",
                "",
                "    // 2. All distinct club names from other sources",
                "    HomeClubs = Table.RenameColumns(Table.SelectColumns(Staging_MatchResults, {\"home_team\"}), {{\"home_team\", \"ClubName\"}}),",
                "    AwayClubs = Table.RenameColumns(Table.SelectColumns(Staging_MatchResults, {\"away_team\"}), {{\"away_team\", \"ClubName\"}}),",
                "    PlayerStatsClubs = Table.RenameColumns(Table.SelectColumns(Staging_PlayerStats, {\"club\"}), {{\"club\", \"ClubName\"}}),",
                "    TransfersDep = Table.RenameColumns(Table.SelectColumns(Staging_Transfers, {\"departure_club\"}), {{\"departure_club\", \"ClubName\"}}),",
                "    TransfersArr = Table.RenameColumns(Table.SelectColumns(Staging_Transfers, {\"arrival_club\"}), {{\"arrival_club\", \"ClubName\"}}),",
                "    StadiumClubs = Table.RenameColumns(Table.SelectColumns(Staging_StadiumAttendance, {\"club\"}), {{\"club\", \"ClubName\"}}),",
                "    SanctionsClubs = Table.RenameColumns(Table.SelectColumns(Staging_Sanctions, {\"club\"}), {{\"club\", \"ClubName\"}}),",
                "    CombinedNames = Table.Combine({HomeClubs, AwayClubs, PlayerStatsClubs, TransfersDep, TransfersArr, StadiumClubs, SanctionsClubs}),",
                "    TrimmedNames = Table.TransformColumns(CombinedNames, {{\"ClubName\", Text.Trim, type text}}),",
                "    DistinctNames = Table.Distinct(TrimmedNames, {\"ClubName\"}),",
                "",
                "    // 3. Keep only names NOT already in DimClub (external clubs)",
                "    ExistingNames = Ligue1Clubs[ClubName],",
                "    ExternalNamesOnly = Table.SelectRows(DistinctNames, each not List.Contains(ExistingNames, [ClubName])),",
                "",
                "    // 4. Build external rows: same columns as Ligue1Clubs, with External = true and nulls elsewhere",
                "    NumLigue1 = Table.RowCount(Ligue1Clubs),",
                "    ExternalWithKey = Table.AddIndexColumn(ExternalNamesOnly, \"ClubKey\", NumLigue1, 1, Int64.Type),",
                "    ExternalWithFlag = Table.AddColumn(ExternalWithKey, \"External\", each true, type logical),",
                "    AddNulls = Table.AddColumn(Table.AddColumn(Table.AddColumn(Table.AddColumn(Table.AddColumn(Table.AddColumn(Table.AddColumn(Table.AddColumn(Table.AddColumn(ExternalWithFlag, \"club_id\", each null), \"city\", each null), \"stadium\", each null), \"capacity\", each null), \"founded\", each null), \"president\", each null), \"coach\", each null), \"budget_ME\", each null), \"colors\", each null),",
                "    ExternalReordered = Table.ReorderColumns(AddNulls, {\"ClubKey\", \"club_id\", \"ClubName\", \"city\", \"stadium\", \"capacity\", \"founded\", \"president\", \"coach\", \"budget_ME\", \"colors\", \"External\"}),",
                "",
                "    // 5. Append external clubs to Ligue 1 clubs",
                "    Final = Table.Combine({Ligue1Clubs, ExternalReordered}),",
                "    #\"Requêtes fusionnées\" = Table.NestedJoin(Final, {\"ClubName\"}, club_logos, {\"club_name\"}, \"club_logos\", JoinKind.LeftOuter),",
                "    #\"club_logos développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées\", \"club_logos\", {\"logo_url\"}, {\"club_logos.logo_url\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"club_logos développé\",{{\"club_logos.logo_url\", \"Club_URL\"}}),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Colonnes renommées\",{{\"Club_URL\", type text}})",
                "in",
                "    #\"Type modifié\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Points/Match",
            "expression": "SUM(FactClubMatch[Points])/COUNT(DimMatch[MatchKey])",
            "formatString": "0",
            "lineageTag": "4730c41a-0fa8-4cdb-a5c2-a09a1aac2aa2"
          },
          {
            "name": "Goals Difference",
            "expression": "SUM(FactClubMatch[GoalsFor])-SUM(FactClubMatch[GoalsAgainst])",
            "formatString": "0",
            "lineageTag": "e76d755d-a20f-404d-958d-5e55d7f4efd0"
          },
          {
            "name": "Win Rate",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNTROWS('FactClubMatch'),",
              "        'FactClubMatch'[Result] = \"W\"",
              "    ),",
              "    COUNT(DimMatch[Matchday])",
              ")",
              ""
            ],
            "lineageTag": "e07933a8-de47-48eb-a678-3aa6241dd93c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Matches Played",
            "expression": "COUNTROWS(FactClubMatch)",
            "formatString": "0",
            "lineageTag": "bde754fb-3bb0-4e8b-9d1d-ef0c9ee9394b"
          },
          {
            "name": "Goals For",
            "expression": "SUM(FactClubMatch[GoalsFor])",
            "formatString": "0",
            "lineageTag": "9db05d30-1a3a-4d73-bd24-5f3d5917cf06"
          },
          {
            "name": "Goals Against",
            "expression": "SUM(FactClubMatch[GoalsAgainst])",
            "formatString": "0",
            "lineageTag": "b4194947-fef3-4a68-9726-d046b5dc7e47"
          },
          {
            "name": "Goals For per Match",
            "expression": "DIVIDE([Goals For], [Matches Played], BLANK())",
            "lineageTag": "1aff75d6-87e5-466b-b9a5-c93920a38882",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Goals Against per Match",
            "expression": "DIVIDE([Goals Against], [Matches Played], BLANK())",
            "lineageTag": "c9d8c2c7-ae96-49d8-979e-5d05dca42f19",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Logo Club HTML",
            "expression": [
              "",
              "VAR ClubKey = SELECTEDVALUE( FactPlayerSeason[ClubKey] )",
              "VAR UrlLogo = LOOKUPVALUE( DimClub[Club_URL], DimClub[ClubKey], ClubKey )",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(UrlLogo),",
              "    \"<div style='display:flex; align-items:center; height:100%;'>",
              "        <img src='\" & UrlLogo & \"' alt='Logo' style='max-width:150px; height:auto;' />",
              "     </div>\",",
              "    \"\"",
              ")"
            ],
            "lineageTag": "5deeb4d0-5930-48be-b3e9-8214122f53fd"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimPlayer",
        "lineageTag": "23348ff3-da27-4639-aa65-e47f47d4af5e",
        "columns": [
          {
            "name": "PlayerKey",
            "dataType": "int64",
            "sourceColumn": "PlayerKey",
            "formatString": "0",
            "lineageTag": "38dc9fcf-7663-4421-8f5c-d215d5725b3e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PlayerId",
            "dataType": "string",
            "sourceColumn": "PlayerId",
            "lineageTag": "ccd01001-5768-4e7e-b97a-4f85017e8d3e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FullName",
            "dataType": "string",
            "sourceColumn": "FullName",
            "lineageTag": "e13561e1-5533-4222-8395-c9bcfe6d595e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Position",
            "dataType": "string",
            "sourceColumn": "Position",
            "lineageTag": "fd7ab515-f5d2-4e9e-a768-cc96b1481f59",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateOfBirth",
            "dataType": "dateTime",
            "sourceColumn": "DateOfBirth",
            "formatString": "Long Date",
            "lineageTag": "79fbab09-f0d7-487a-948a-30a554f88dc3",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "e78ddb87-cab5-4ab5-a6fc-ce671cf8ebf4",
                "defaultHierarchy": {
                  "table": "LocalDateTable_1ddaff7e-1747-4fb5-943c-4d38455cfbb1",
                  "hierarchy": "Hiérarchie de dates"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Nationality",
            "dataType": "string",
            "sourceColumn": "Nationality",
            "lineageTag": "e14419d8-1a3b-4f10-a6c2-7012d090c97a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MarketValue",
            "dataType": "double",
            "sourceColumn": "MarketValue",
            "lineageTag": "6ed40199-4310-4be8-baa3-4a149a3d4647",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Age",
            "dataType": "int64",
            "sourceColumn": "Age",
            "formatString": "0",
            "lineageTag": "abd03297-aeb3-40d6-bf4b-9f12b6a29a8e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimPlayer",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Staging_PlayerStats,",
                "    #\"Doublons supprimés\" = Table.Distinct(Source, {\"player_id\", \"full_name\", \"position\"}),",
                "    #\"Doublons supprimés1\" = Table.Distinct(#\"Doublons supprimés\", {\"player_id\"}),",
                "    #\"Autres colonnes supprimées\" = Table.SelectColumns(#\"Doublons supprimés1\",{\"player_id\", \"full_name\", \"position\"}),",
                "    #\"Index ajouté\" = Table.AddIndexColumn(#\"Autres colonnes supprimées\", \"Index\", 0, 1, Int64.Type),",
                "    #\"Colonnes permutées\" = Table.ReorderColumns(#\"Index ajouté\",{\"Index\", \"player_id\", \"full_name\", \"position\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Colonnes permutées\",{{\"Index\", \"PlayerKey\"}, {\"player_id\", \"PlayerId\"}, {\"full_name\", \"FullName\"}, {\"position\", \"Position\"}}),",
                "    #\"Requêtes fusionnées\" = Table.NestedJoin(#\"Colonnes renommées\", {\"PlayerId\"}, Staging_Players, {\"player_id\"}, \"Staging_Players\", JoinKind.LeftOuter),",
                "    #\"Staging_Players développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées\", \"Staging_Players\", {\"date_of_birth\", \"nationality\", \"market_value_ME\"}, {\"Staging_Players.date_of_birth\", \"Staging_Players.nationality\", \"Staging_Players.market_value_ME\"}),",
                "    #\"Colonnes renommées1\" = Table.RenameColumns(#\"Staging_Players développé\",{{\"Staging_Players.date_of_birth\", \"Age\"}, {\"Staging_Players.nationality\", \"Nationality\"}, {\"Staging_Players.market_value_ME\", \"MarketValue\"}}),",
                "    #\"FullName counts\" = Table.Group(#\"Colonnes renommées1\", {\"FullName\"}, {{\"Count\", each Table.RowCount(_), Int64.Type}}),",
                "    #\"Counts fusionnés\" = Table.NestedJoin(#\"Colonnes renommées1\", {\"FullName\"}, #\"FullName counts\", {\"FullName\"}, \"Counts\", JoinKind.LeftOuter),",
                "    #\"Counts développés\" = Table.ExpandTableColumn(#\"Counts fusionnés\", \"Counts\", {\"Count\"}, {\"Count\"}),",
                "    #\"FullName unique\" = Table.AddColumn(#\"Counts développés\", \"FullNameUnique\", each if [Count] > 1 then [FullName] & \" (\" & (if [Nationality] = null or [Nationality] = \"\" then \"?\" else [Nationality]) & \")\" else [FullName], type text),",
                "    #\"Colonnes Count FullName supprimées\" = Table.RemoveColumns(#\"FullName unique\", {\"Count\", \"FullName\"}),",
                "    #\"FullName renommé\" = Table.RenameColumns(#\"Colonnes Count FullName supprimées\", {{\"FullNameUnique\", \"FullName\"}}),",
                "    Personnalisé1 = Table.AddColumn(#\"FullName renommé\", \"Personnalisé\", each Number.RoundDown(Duration.TotalDays(DateTime.Date(DateTime.LocalNow()) - [Age]) / 365.25)),",
                "    Personnalisé2 = Table.TransformColumnTypes(#\"Personnalisé1\",{{\"Personnalisé\", Int64.Type}}),",
                "    Personnalisé3 = Table.RenameColumns(#\"Personnalisé2\",{{\"Age\", \"DateOfBirth\"}, {\"Personnalisé\", \"Age\"}})",
                "in",
                "    Personnalisé3"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_1ddaff7e-1747-4fb5-943c-4d38455cfbb1",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "3f635352-a718-4721-81ff-f61846a4c70e",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "cce102cf-eaed-4654-8da8-d0f56f784eca",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Année",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "5033f011-ac1d-4099-813d-b03143a22fd0",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoMois",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "35c50628-319b-496f-8483-6ce546964191",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mois",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "NoMois",
            "lineageTag": "904d55b7-8e8d-4bfd-8f64-57ca08d8ed71",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoTrimestre",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([NoMois] + 2) / 3)",
            "lineageTag": "6fcac7e1-abff-4f32-8e6e-5551f288a8ef",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [NoTrimestre]",
            "sortByColumn": "NoTrimestre",
            "lineageTag": "7ecffd40-57af-491f-91cf-1afeb4ed2f64",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Jour",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "0f61f66e-a991-454e-b0cc-fcfd777c5e6d",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_1ddaff7e-1747-4fb5-943c-4d38455cfbb1",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('DimPlayer'[DateOfBirth])), 1, 1), Date(Year(MAX('DimPlayer'[DateOfBirth])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "lineageTag": "4db3a1ee-90ee-4240-bbb0-7a112ef02955",
            "levels": [
              {
                "name": "Année",
                "ordinal": 0,
                "column": "Année",
                "lineageTag": "feff8430-ab53-4b48-873e-9347bff4408b"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "87434428-5d53-40fb-967d-64840250486f"
              },
              {
                "name": "Mois",
                "ordinal": 2,
                "column": "Mois",
                "lineageTag": "325b7724-dd64-44bc-8c87-a6eee3c81456"
              },
              {
                "name": "Jour",
                "ordinal": 3,
                "column": "Jour",
                "lineageTag": "8e95603a-7290-4029-b6a2-a2e07711a138"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "DimMatch",
        "lineageTag": "a2035b37-b257-4fec-a383-2666d30a5689",
        "columns": [
          {
            "name": "MatchKey",
            "dataType": "string",
            "sourceColumn": "MatchKey",
            "lineageTag": "1056a6f4-cd24-4f81-a40d-1378e6dd783c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Matchday",
            "dataType": "int64",
            "sourceColumn": "Matchday",
            "formatString": "0",
            "lineageTag": "b067b54e-a4e9-4a7c-9593-ec1c3349879b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "HomeClubKey",
            "dataType": "int64",
            "sourceColumn": "HomeClubKey",
            "formatString": "0",
            "lineageTag": "265f3f5b-03dc-40b1-8346-115fee1d623a",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AwayClubKey",
            "dataType": "int64",
            "sourceColumn": "AwayClubKey",
            "formatString": "0",
            "lineageTag": "8b839e79-d576-45d3-b7dc-bede9ab395eb",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Stadium",
            "dataType": "string",
            "sourceColumn": "Stadium",
            "lineageTag": "57c0ff26-5954-41c6-9b86-c0ef5a50f2c5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Referee",
            "dataType": "string",
            "sourceColumn": "Referee",
            "lineageTag": "1fd07a7e-c66f-40a2-860b-6946f379928f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Attendance",
            "dataType": "int64",
            "sourceColumn": "Attendance",
            "formatString": "0",
            "lineageTag": "c3548442-9ea1-429a-9734-9e4f3600337d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateKey",
            "dataType": "string",
            "sourceColumn": "DateKey",
            "lineageTag": "8c92ad2d-8313-4766-9fd0-368f80d29518",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimMatch",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Staging_MatchResults,",
                "    #\"Requêtes fusionnées\" = Table.NestedJoin(Source, {\"home_team\"}, DimClub, {\"ClubName\"}, \"DimClub\", JoinKind.LeftOuter),",
                "    #\"DimClub développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées\", \"DimClub\", {\"ClubKey\"}, {\"DimClub.ClubKey\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"DimClub développé\",{{\"DimClub.ClubKey\", \"HomeClubKey\"}}),",
                "    #\"Requêtes fusionnées1\" = Table.NestedJoin(#\"Colonnes renommées\", {\"away_team\"}, DimClub, {\"ClubName\"}, \"DimClub\", JoinKind.LeftOuter),",
                "    #\"DimClub développé1\" = Table.ExpandTableColumn(#\"Requêtes fusionnées1\", \"DimClub\", {\"ClubKey\"}, {\"DimClub.ClubKey\"}),",
                "    #\"Colonnes renommées1\" = Table.RenameColumns(#\"DimClub développé1\",{{\"DimClub.ClubKey\", \"AwayClubKey\"}, {\"match_id\", \"MatchKey\"}, {\"matchday\", \"Matchday\"}}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Colonnes renommées1\",{\"home_team\", \"away_team\", \"home_score\", \"away_score\"}),",
                "    #\"Colonnes permutées\" = Table.ReorderColumns(#\"Colonnes supprimées\",{\"MatchKey\", \"Matchday\", \"match_date\", \"HomeClubKey\", \"AwayClubKey\", \"stadium\", \"referee\", \"attendance\"}),",
                "    #\"Colonnes renommées2\" = Table.RenameColumns(#\"Colonnes permutées\",{{\"match_date\", \"MatchDate\"}, {\"stadium\", \"Stadium\"}, {\"referee\", \"Referee\"}, {\"attendance\", \"Attendance\"}}),",
                "    #\"Requêtes fusionnées2\" = Table.NestedJoin(#\"Colonnes renommées2\", {\"MatchDate\"}, DimDate, {\"Date\"}, \"DimDate\", JoinKind.LeftOuter),",
                "    #\"DimDate développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées2\", \"DimDate\", {\"DateKey\"}, {\"DimDate.DateKey\"}),",
                "    #\"Colonnes renommées3\" = Table.RenameColumns(#\"DimDate développé\",{{\"DimDate.DateKey\", \"DateKey\"}}),",
                "    #\"Colonnes permutées1\" = Table.ReorderColumns(#\"Colonnes renommées3\",{\"MatchKey\", \"Matchday\", \"MatchDate\", \"DateKey\", \"HomeClubKey\", \"AwayClubKey\", \"Stadium\", \"Referee\", \"Attendance\"}),",
                "    #\"Colonnes supprimées1\" = Table.RemoveColumns(#\"Colonnes permutées1\",{\"MatchDate\"})",
                "in",
                "    #\"Colonnes supprimées1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Matches per Matchday",
            "expression": "COUNTROWS(DimMatch)",
            "formatString": "0",
            "lineageTag": "2e84e157-3360-4f0a-a416-e5a380f1b6d1"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Staging_Field_Players",
        "isHidden": true,
        "lineageTag": "ecfe591a-81d5-4c9d-816e-4f10cc90857e",
        "columns": [
          {
            "name": "player_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "player_id",
            "lineageTag": "817ba786-e4b3-4741-bf11-466c996236e1",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "last_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "last_name",
            "lineageTag": "49379a58-1a4c-4779-bb3d-5045d359b65f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "first_name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "first_name",
            "lineageTag": "08d79c3b-945c-4b82-bec8-7ff4152bf3c2",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date_of_birth",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "date_of_birth",
            "formatString": "Long Date",
            "lineageTag": "291d3859-9424-4d27-adb9-71eeb7218b9a",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "7a8e5622-81d3-4216-862d-f6a915c4d8b3",
                "defaultHierarchy": {
                  "table": "LocalDateTable_e2962b62-a583-45df-b831-8426c7093111",
                  "hierarchy": "Hiérarchie de dates"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "nationality",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "nationality",
            "lineageTag": "f5aff080-e4bc-4190-a864-c045bd297fca",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "club_id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "club_id",
            "lineageTag": "1b623d30-7311-48c7-9315-297c4e6ec170",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "club",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "club",
            "lineageTag": "ef216a56-1928-4cc0-9cad-980c6e357a8f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "position",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "position",
            "lineageTag": "af22a029-d13c-4598-8563-cd7aa5b30c59",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "jersey_number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "jersey_number",
            "formatString": "0",
            "lineageTag": "2cd47b26-f5f9-41ef-ad36-02d4ca45925a",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "height_cm",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "height_cm",
            "lineageTag": "46023d54-d1dd-4e84-a935-86c10a267994",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "weight_kg",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "weight_kg",
            "formatString": "0",
            "lineageTag": "5b8b9b30-4c12-4503-bbbf-027202a33b70",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "strong_foot",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "strong_foot",
            "lineageTag": "2d14048d-3059-4479-8646-f0f9edfe7041",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "club_arrival_date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "club_arrival_date",
            "formatString": "Long Date",
            "lineageTag": "d8d86cff-8793-4e32-99dd-bcce3f03740e",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "cbfe5764-4b1c-4088-8926-48272ff2148c",
                "defaultHierarchy": {
                  "table": "LocalDateTable_d5744ca4-8cac-40a1-a228-c2696a0c6c9e",
                  "hierarchy": "Hiérarchie de dates"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "market_value_ME",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "market_value_ME",
            "lineageTag": "dfb1a08c-34d5-4cf7-9a0b-3750aa0844e9",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Staging_Field_Players",
            "mode": "import",
            "queryGroup": "Staging Queries",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\frede\\Downloads\\players.xlsx\"), null, true),",
                "    Field_Players_Sheet = Source{[Item=\"Field_Players\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Field_Players_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"player_id\", type text}, {\"last_name\", type text}, {\"first_name\", type text}, {\"date_of_birth\", type date}, {\"nationality\", type text}, {\"club_id\", type text}, {\"club\", type text}, {\"position\", type text}, {\"jersey_number\", Int64.Type}, {\"height_cm\", type any}, {\"weight_kg\", Int64.Type}, {\"strong_foot\", type text}, {\"club_arrival_date\", type date}, {\"market_value_ME\", type number}})",
                "in",
                "    #\"Type modifié\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_e2962b62-a583-45df-b831-8426c7093111",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "51d0dd4b-38a4-4064-9dd3-c6a61862affa",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "132c50c5-2c66-4f4a-a880-a2173e7cb614",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Année",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "4544cf86-6edb-4b96-a130-f09918aee018",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoMois",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "d876da9e-ba83-4b6a-88ae-d768e022bbcb",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mois",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "NoMois",
            "lineageTag": "872d66dc-4b73-4361-ae3e-66a92cc7e7df",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoTrimestre",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([NoMois] + 2) / 3)",
            "lineageTag": "a63a0114-fa2a-4401-8a1d-e0522ce57b81",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [NoTrimestre]",
            "sortByColumn": "NoTrimestre",
            "lineageTag": "27b6cbb7-4fd8-4079-bab4-227f550e2104",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Jour",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "7004134f-e453-443f-962c-ca92fec5ade4",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_e2962b62-a583-45df-b831-8426c7093111",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Staging_Field_Players'[date_of_birth])), 1, 1), Date(Year(MAX('Staging_Field_Players'[date_of_birth])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "lineageTag": "3f3f9adb-4e67-4e39-b233-b98e53e1c340",
            "levels": [
              {
                "name": "Année",
                "ordinal": 0,
                "column": "Année",
                "lineageTag": "6f06ab1a-adb1-4ea8-8a0a-42b874799ac5"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "45fbdb82-98cd-4658-afa3-9925bbcf1d93"
              },
              {
                "name": "Mois",
                "ordinal": 2,
                "column": "Mois",
                "lineageTag": "2009263d-5954-4e26-a1f9-67bd717d8810"
              },
              {
                "name": "Jour",
                "ordinal": 3,
                "column": "Jour",
                "lineageTag": "0708ad8d-eba7-4768-afae-24992cd31253"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_d5744ca4-8cac-40a1-a228-c2696a0c6c9e",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "0f628db8-6e3a-42e5-a448-6607c9f7413d",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "da759d46-99e9-48ae-964c-746679899167",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Année",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "8bcba8a1-621c-45d7-871a-52d6e1d6a00c",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoMois",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "ae09ee4e-e3a9-442b-b0f9-d8b87515f37c",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mois",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "NoMois",
            "lineageTag": "40468d37-debe-46e2-b9f2-13ffb5fb432f",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NoTrimestre",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([NoMois] + 2) / 3)",
            "lineageTag": "ed20b7b0-74ea-46a1-a164-fba08795b541",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [NoTrimestre]",
            "sortByColumn": "NoTrimestre",
            "lineageTag": "4bb5330e-dbf3-40fd-b962-f5b5bceeca73",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Jour",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "06eaeb0a-8aa7-4de7-a36d-b1008b51c598",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_d5744ca4-8cac-40a1-a228-c2696a0c6c9e",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Staging_Field_Players'[club_arrival_date])), 1, 1), Date(Year(MAX('Staging_Field_Players'[club_arrival_date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "lineageTag": "dfa8c847-024a-4cc4-b3d8-8bb2131303dc",
            "levels": [
              {
                "name": "Année",
                "ordinal": 0,
                "column": "Année",
                "lineageTag": "bfc5e672-4467-468b-9169-dceb478c5fb7"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "0c678193-4a06-44bd-ba0e-4b08f5aaf13b"
              },
              {
                "name": "Mois",
                "ordinal": 2,
                "column": "Mois",
                "lineageTag": "f1921df7-be71-437c-9bae-1877724536fd"
              },
              {
                "name": "Jour",
                "ordinal": 3,
                "column": "Jour",
                "lineageTag": "9d14106e-a5e2-4457-8350-148cba616720"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "FactClubMatch",
        "lineageTag": "aed0c750-7077-48d8-bed0-5532aeab987f",
        "columns": [
          {
            "name": "MatchKey",
            "dataType": "string",
            "sourceColumn": "MatchKey",
            "lineageTag": "2de14031-4fd1-4b31-9cb8-a85fa36329be",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ClubKey",
            "dataType": "int64",
            "sourceColumn": "ClubKey",
            "formatString": "0",
            "lineageTag": "f50ab170-2c0d-4b0f-b21a-5461dbb1db95",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "IsHome",
            "dataType": "boolean",
            "sourceColumn": "IsHome",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f424785d-3a97-44aa-9e03-007c18031c9f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Points",
            "dataType": "int64",
            "sourceColumn": "Points",
            "formatString": "0",
            "lineageTag": "c595e46b-2ea6-41c2-96ca-4ed23ad69107",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GoalsFor",
            "dataType": "int64",
            "sourceColumn": "GoalsFor",
            "formatString": "0",
            "lineageTag": "f9f5119d-be62-43d0-a1bc-10e0d5bf5853",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GoalsAgainst",
            "dataType": "int64",
            "sourceColumn": "GoalsAgainst",
            "formatString": "0",
            "lineageTag": "12ac3060-b5d4-4cef-bd11-88359c1c1739",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Result",
            "dataType": "string",
            "sourceColumn": "Result",
            "lineageTag": "529f2fa3-dfd1-455e-bb05-2446d8f296d8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Goal difference",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "FactClubMatch[GoalsFor] - FactClubMatch[GoalsAgainst]",
            "formatString": "0",
            "lineageTag": "01a5c22b-7162-4260-81dd-004e2c5c974a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactClubMatch",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "type": "m",
              "expression": [
                "// FactClubMatch: need HomeClubKey, AwayClubKey from merge first",
                "let",
                "  Merged = Table.NestedJoin(Staging_MatchResults, {\"home_team\"}, DimClub, {\"ClubName\"}, \"Home\", JoinKind.LeftOuter),",
                "  ExpandedHome = Table.ExpandTableColumn(Merged, \"Home\", {\"ClubKey\"}, {\"HomeClubKey\"}),",
                "  Merged2 = Table.NestedJoin(ExpandedHome, {\"away_team\"}, DimClub, {\"ClubName\"}, \"Away\", JoinKind.LeftOuter),",
                "  ExpandedAway = Table.ExpandTableColumn(Merged2, \"Away\", {\"ClubKey\"}, {\"AwayClubKey\"}),",
                "  HomeRows = Table.AddColumn(ExpandedAway, \"IsHome\", each true),",
                "  HomeRows2 = Table.SelectColumns(HomeRows, {\"match_id\", \"HomeClubKey\", \"IsHome\", \"home_score\", \"away_score\"}),",
                "  HomePoints = Table.AddColumn(HomeRows2, \"Points\", each if [home_score] > [away_score] then 3 else if [home_score] = [away_score] then 1 else 0),",
                "  HomeGFGA = Table.AddColumn(Table.AddColumn(HomePoints, \"GoalsFor\", each [home_score]), \"GoalsAgainst\", each [away_score]),",
                "  HomeResult = Table.AddColumn(HomeGFGA, \"Result\", each if [home_score] > [away_score] then \"W\" else if [home_score] = [away_score] then \"D\" else \"L\"),",
                "  HomeFinal = Table.SelectColumns(Table.RenameColumns(HomeResult, {{\"match_id\", \"MatchKey\"}, {\"HomeClubKey\", \"ClubKey\"}}), {\"MatchKey\", \"ClubKey\", \"IsHome\", \"Points\", \"GoalsFor\", \"GoalsAgainst\", \"Result\"}),",
                "  AwayRows = Table.AddColumn(ExpandedAway, \"IsHome\", each false),",
                "  AwayRows2 = Table.SelectColumns(AwayRows, {\"match_id\", \"AwayClubKey\", \"IsHome\", \"home_score\", \"away_score\"}),",
                "  AwayPoints = Table.AddColumn(AwayRows2, \"Points\", each if [away_score] > [home_score] then 3 else if [away_score] = [home_score] then 1 else 0),",
                "  AwayGFGA = Table.AddColumn(Table.AddColumn(AwayPoints, \"GoalsFor\", each [away_score]), \"GoalsAgainst\", each [home_score]),",
                "  AwayResult = Table.AddColumn(AwayGFGA, \"Result\", each if [away_score] > [home_score] then \"W\" else if [away_score] = [home_score] then \"D\" else \"L\"),",
                "  AwayFinal = Table.SelectColumns(Table.RenameColumns(AwayResult, {{\"match_id\", \"MatchKey\"}, {\"AwayClubKey\", \"ClubKey\"}}), {\"MatchKey\", \"ClubKey\", \"IsHome\", \"Points\", \"GoalsFor\", \"GoalsAgainst\", \"Result\"}),",
                "  Combined = Table.Combine({HomeFinal, AwayFinal})",
                "in Combined"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Away Points",
            "expression": "CALCULATE(SUM(FactClubMatch[Points]), FactClubMatch[IsHome] = FALSE())",
            "formatString": "0",
            "lineageTag": "29bcb77f-ab81-4575-a2f6-23991550565a"
          },
          {
            "name": "Cumulative Points",
            "expression": [
              "",
              "VAR CurrentMatchday = MAX(DimMatch[Matchday])",
              "RETURN",
              "    CALCULATE(",
              "        SUM(FactClubMatch[Points]),",
              "        DimMatch[Matchday] <= CurrentMatchday,",
              "        ALL(DimMatch[Matchday])",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "0f34f74d-74ce-47f6-9132-0c6f412fe459"
          },
          {
            "name": "Discipline HTML",
            "expression": [
              "",
              "-- Cards from FactPlayerSeason (player match statistics)",
              "VAR vYellowCards = SUM(FactPlayerSeason[YellowCards])",
              "VAR vRedCards = SUM(FactPlayerSeason[RedCards])",
              "",
              "-- Sanctions from FactSanction (official disciplinary actions)",
              "VAR vSuspensions = SUM(FactSanction[SuspensionMatches])",
              "VAR vFines = SUM(FactSanction[FineEuros])",
              "",
              "-- Format fines (handle blank/null)",
              "VAR vFinesFmt = ",
              "    IF (",
              "        ISBLANK ( vFines ) || vFines = 0,",
              "        \"0\",",
              "        FORMAT ( vFines, \"#,0\" ) & \" €\"",
              "    )",
              "",
              "-- Format other values (handle blank/null)",
              "VAR vYellowFmt = IF ( ISBLANK ( vYellowCards ) || vYellowCards = 0, \"0\", FORMAT ( vYellowCards, \"#,0\" ) )",
              "VAR vRedFmt = IF ( ISBLANK ( vRedCards ) || vRedCards = 0, \"0\", FORMAT ( vRedCards, \"#,0\" ) )",
              "VAR vSuspendFmt = IF ( ISBLANK ( vSuspensions ) || vSuspensions = 0, \"0\", FORMAT ( vSuspensions, \"#,0\" ) )",
              "",
              "RETURN",
              "\"",
              "<style>",
              "  * { box-sizing: border-box; }",
              "  body {",
              "    margin: 0;",
              "    padding: 10px;",
              "    font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;",
              "    background: transparent;",
              "  }",
              "  .disc-widget {",
              "    display: flex;",
              "    flex-direction: column;",
              "    gap: 8px;",
              "  }",
              "  .disc-title {",
              "    font-size: 12px;",
              "    font-weight: 600;",
              "    color: #1a1a1a;",
              "    text-align: center;",
              "    margin-bottom: 2px;",
              "  }",
              "  .disc-cards {",
              "    display: flex;",
              "    flex-wrap: wrap;",
              "    gap: 6px;",
              "    justify-content: center;",
              "  }",
              "  .disc-card {",
              "    flex: 1 1 90px;",
              "    min-width: 70px;",
              "    max-width: 110px;",
              "    padding: 10px 8px;",
              "    border-radius: 8px;",
              "    text-align: center;",
              "    box-shadow: 0 2px 6px rgba(0,0,0,0.1);",
              "    transition: transform 0.2s ease;",
              "  }",
              "  .disc-card:hover {",
              "    transform: translateY(-2px);",
              "    box-shadow: 0 4px 8px rgba(0,0,0,0.15);",
              "  }",
              "  .disc-yellow { ",
              "    background: linear-gradient(135deg, #FFFFFF 0%, #FFF9E6 100%);",
              "    border-left: 4px solid #FFC107;",
              "  }",
              "  .disc-red { ",
              "    background: linear-gradient(135deg, #FFFFFF 0%, #FFEBEE 100%);",
              "    border-left: 4px solid #D64554;",
              "  }",
              "  .disc-suspend { ",
              "    background: linear-gradient(135deg, #FFFFFF 0%, #F3F2F1 100%);",
              "    border-left: 4px solid #808080;",
              "  }",
              "  .disc-fines { ",
              "    background: linear-gradient(135deg, #FFFFFF 0%, #E8F5E9 100%);",
              "    border-left: 4px solid #1AAB40;",
              "  }",
              "  .disc-icon {",
              "    font-size: 20px;",
              "    margin-bottom: 3px;",
              "    line-height: 1;",
              "  }",
              "  .disc-value {",
              "    font-size: 20px;",
              "    font-weight: 700;",
              "    color: #1a1a1a;",
              "    margin-bottom: 2px;",
              "  }",
              "  .disc-label {",
              "    font-size: 10px;",
              "    color: #404040;",
              "    text-transform: uppercase;",
              "    letter-spacing: 0.5px;",
              "  }",
              "</style>",
              "<div class='disc-widget'>",
              "  <div class='disc-title'>Season Discipline</div>",
              "  <div class='disc-cards'>",
              "    <div class='disc-card disc-yellow'>",
              "      <div class='disc-icon'>🟨</div>",
              "      <div class='disc-value'>\" & vYellowFmt & \"</div>",
              "      <div class='disc-label'>Yellow Cards</div>",
              "    </div>",
              "    <div class='disc-card disc-red'>",
              "      <div class='disc-icon'>🟥</div>",
              "      <div class='disc-value'>\" & vRedFmt & \"</div>",
              "      <div class='disc-label'>Red Cards</div>",
              "    </div>",
              "    <div class='disc-card disc-suspend'>",
              "      <div class='disc-icon'>⛔</div>",
              "      <div class='disc-value'>\" & vSuspendFmt & \"</div>",
              "      <div class='disc-label'>Suspensions</div>",
              "    </div>",
              "    <div class='disc-card disc-fines'>",
              "      <div class='disc-icon'>€</div>",
              "      <div class='disc-value'>\" & vFinesFmt & \"</div>",
              "      <div class='disc-label'>Total Fines</div>",
              "    </div>",
              "  </div>",
              "  <div style='font-size: 9px; color: #404040; text-align: center; margin-top: 4px;'>",
              "    Cards: Match statistics | Sanctions: Official disciplinary actions",
              "  </div>",
              "  </div>",
              "</div>",
              "\""
            ],
            "lineageTag": "af3723b7-9191-4b73-8049-f27a5fdfa9af"
          },
          {
            "name": "Final Rank",
            "expression": [
              "",
              "VAR TotalPoints = [Total Points]",
              "VAR RankedClubs = ",
              "    ADDCOLUMNS(",
              "        ALL(DimClub[ClubKey], DimClub[ClubName]),",
              "        \"@Points\", CALCULATE([Total Points], ALLSELECTED(DimMatch))",
              "    )",
              "RETURN",
              "    RANKX(RankedClubs, [@Points], TotalPoints, DESC, Dense)"
            ],
            "formatString": "0",
            "lineageTag": "0ad40dd0-896a-4e70-bd8f-06ecb2949a2b"
          },
          {
            "name": "Home Points",
            "expression": "CALCULATE(SUM(FactClubMatch[Points]), FactClubMatch[IsHome] = TRUE())",
            "formatString": "0",
            "lineageTag": "ca0054fa-2eeb-4b68-a9ce-bb785d742907"
          },
          {
            "name": "Opponent Final Rank",
            "expression": [
              "",
              "VAR OpponentClubKey = ",
              "    CALCULATE(",
              "        MAX(FactClubMatch[ClubKey]),",
              "        ALLEXCEPT(FactClubMatch, FactClubMatch[MatchKey]),",
              "        FactClubMatch[ClubKey] <> MAX(FactClubMatch[ClubKey])",
              "    )",
              "RETURN",
              "    LOOKUPVALUE(StandingsFinal[FinalRank], StandingsFinal[ClubKey], OpponentClubKey)"
            ],
            "lineageTag": "21006061-e82c-4fb8-ac60-5a515cdaffd2"
          },
          {
            "name": "Rank at Matchday",
            "expression": [
              "",
              "VAR CurrentMatchday = MAX(DimMatch[Matchday])",
              "VAR CurrentPoints = [Cumulative Points]",
              "VAR AllClubs = ",
              "    ADDCOLUMNS(",
              "        ALL(DimClub[ClubKey], DimClub[ClubName]),",
              "        \"@Points\", ",
              "        CALCULATE(",
              "            [Cumulative Points],",
              "            DimMatch[Matchday] <= CurrentMatchday,",
              "            ALL(DimMatch[Matchday])",
              "        )",
              "    )",
              "RETURN",
              "    RANKX(AllClubs, [@Points], CurrentPoints, DESC, Dense)"
            ],
            "formatString": "0",
            "lineageTag": "c2608aa8-7cc5-4890-9142-4402e41009a2"
          },
          {
            "name": "Rank Points HTML",
            "expression": [
              "",
              "-- Calculate total points",
              "VAR vTotalPoints = SUM(FactClubMatch[Points])",
              "",
              "-- Calculate final rank",
              "VAR vFinalRank = ",
              "    VAR TotalPoints = vTotalPoints",
              "    VAR RankedClubs = ",
              "        ADDCOLUMNS(",
              "            ALL(DimClub[ClubKey], DimClub[ClubName]),",
              "            \"@Points\", CALCULATE(SUM(FactClubMatch[Points]), ALLSELECTED(DimMatch))",
              "        )",
              "    RETURN",
              "        RANKX(RankedClubs, [@Points], TotalPoints, DESC, Dense)",
              "",
              "-- Get club name (optional, for display)",
              "VAR vClubName = SELECTEDVALUE(DimClub[ClubName], \"League\")",
              "",
              "-- Format rank with ordinal suffix (1st, 2nd, 3rd, etc.)",
              "VAR vRankFmt = ",
              "    IF (",
              "        ISBLANK ( vFinalRank ) || vFinalRank = 0,",
              "        \"–\",",
              "        VAR RankNum = vFinalRank",
              "        VAR LastDigit = MOD ( RankNum, 10 )",
              "        VAR LastTwoDigits = MOD ( RankNum, 100 )",
              "        VAR Suffix = ",
              "            IF (",
              "                LastTwoDigits >= 11 && LastTwoDigits <= 13,",
              "                \"th\",",
              "                IF (",
              "                    LastDigit = 1, \"st\",",
              "                    IF ( LastDigit = 2, \"nd\",",
              "                        IF ( LastDigit = 3, \"rd\", \"th\" )",
              "                    )",
              "                )",
              "            )",
              "        RETURN",
              "            FORMAT ( RankNum, \"#,0\" ) & Suffix",
              "    )",
              "",
              "-- Format points",
              "VAR vPointsFmt = ",
              "    IF (",
              "        ISBLANK ( vTotalPoints ) || vTotalPoints = 0,",
              "        \"0\",",
              "        FORMAT ( vTotalPoints, \"#,0\" )",
              "    )",
              "",
              "-- Determine rank color (theme: good / neutral / orange / bad)",
              "VAR vRankColor = ",
              "    IF (",
              "        ISBLANK ( vFinalRank ),",
              "        \"#808080\",",
              "        IF ( vFinalRank <= 3, \"#1AAB40\",",
              "            IF ( vFinalRank <= 10, \"#FFC107\",",
              "                IF ( vFinalRank <= 17, \"#E65C00\", \"#D64554\" )",
              "            )",
              "        )",
              "    )",
              "",
              "RETURN",
              "\"",
              "<style>",
              "  * { box-sizing: border-box; }",
              "  body {",
              "    margin: 0;",
              "    padding: 10px;",
              "    font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;",
              "    background: transparent;",
              "  }",
              "  .rank-points-widget {",
              "    display: flex;",
              "    flex-direction: column;",
              "    gap: 8px;",
              "  }",
              "  .rank-title {",
              "    font-size: 12px;",
              "    font-weight: 600;",
              "    color: #1a1a1a;",
              "    text-align: center;",
              "    margin-bottom: 2px;",
              "  }",
              "  .rank-cards {",
              "    display: flex;",
              "    flex-wrap: wrap;",
              "    gap: 6px;",
              "    justify-content: center;",
              "  }",
              "  .rank-card, .points-card {",
              "    flex: 1 1 90px;",
              "    min-width: 70px;",
              "    max-width: 110px;",
              "    padding: 10px 8px;",
              "    border-radius: 8px;",
              "    text-align: center;",
              "    box-shadow: 0 2px 6px rgba(0,0,0,0.1);",
              "    transition: transform 0.2s ease;",
              "  }",
              "  .rank-card:hover, .points-card:hover {",
              "    transform: translateY(-2px);",
              "    box-shadow: 0 4px 8px rgba(0,0,0,0.15);",
              "  }",
              "  .rank-card {",
              "    background: linear-gradient(135deg, #FFFFFF 0%, #F3F2F1 100%);",
              "    border-left: 4px solid \" & vRankColor & \";",
              "  }",
              "  .points-card {",
              "    background: linear-gradient(135deg, #E8F4FC 0%, #D0E8F7 100%);",
              "    border-left: 4px solid #0066CC;",
              "  }",
              "  .card-icon {",
              "    font-size: 18px;",
              "    margin-bottom: 2px;",
              "    line-height: 1;",
              "  }",
              "  .card-value {",
              "    font-size: 18px;",
              "    font-weight: 700;",
              "    color: #1a1a1a;",
              "    margin-bottom: 2px;",
              "  }",
              "  .card-label {",
              "    font-size: 10px;",
              "    color: #404040;",
              "    text-transform: uppercase;",
              "    letter-spacing: 0.5px;",
              "  }",
              "</style>",
              "<div class='rank-points-widget'>",
              "  <div class='rank-title'>Season Performance</div>",
              "  <div class='rank-cards'>",
              "    <div class='rank-card'>",
              "      <div class='card-icon'>🏆</div>",
              "      <div class='card-value'>\" & vRankFmt & \"</div>",
              "      <div class='card-label'>Final Rank</div>",
              "    </div>",
              "    <div class='points-card'>",
              "      <div class='card-icon'>⚽</div>",
              "      <div class='card-value'>\" & vPointsFmt & \"</div>",
              "      <div class='card-label'>Total Points</div>",
              "    </div>",
              "  </div>",
              "</div>",
              "\""
            ],
            "lineageTag": "6d0d666c-90a0-452a-b801-02144bc7e0dc"
          },
          {
            "name": "Top Players HTML",
            "expression": [
              "",
              "-- Note: FactPlayerSeason has one row per player with Goals and Assists",
              "-- It's possible (and valid) for the same player to lead in both categories",
              "-- This measure finds top scorer and top assister separately",
              "",
              "-- Get top scorer (respects club filter from slicer)",
              "VAR PlayersByGoals = ",
              "    ADDCOLUMNS(",
              "        VALUES(FactPlayerSeason[PlayerKey]),",
              "        \"@Goals\", ",
              "        CALCULATE(SUM(FactPlayerSeason[Goals])),",
              "        \"@PlayerName\",",
              "        CALCULATE(MAX(DimPlayer[FullName]))",
              "    )",
              "VAR TopScorerTbl = ",
              "    TOPN(1, PlayersByGoals, [@Goals], DESC)",
              "VAR vTopScorerKey = ",
              "    IF(COUNTROWS(TopScorerTbl) > 0, MAXX(TopScorerTbl, FactPlayerSeason[PlayerKey]), BLANK())",
              "VAR vTopScorerName = ",
              "    IF(",
              "        NOT ISBLANK(vTopScorerKey),",
              "        CALCULATE(MAX(DimPlayer[FullName]), DimPlayer[PlayerKey] = vTopScorerKey),",
              "        \"–\"",
              "    )",
              "VAR vTopScorerGoals = ",
              "    IF(",
              "        NOT ISBLANK(vTopScorerKey),",
              "        CALCULATE(SUM(FactPlayerSeason[Goals]), FactPlayerSeason[PlayerKey] = vTopScorerKey),",
              "        0",
              "    )",
              "",
              "-- Get top assister (respects club filter from slicer)",
              "VAR PlayersByAssists = ",
              "    ADDCOLUMNS(",
              "        VALUES(FactPlayerSeason[PlayerKey]),",
              "        \"@Assists\", ",
              "        CALCULATE(SUM(FactPlayerSeason[Assists])),",
              "        \"@PlayerName\",",
              "        CALCULATE(MAX(DimPlayer[FullName]))",
              "    )",
              "VAR TopAssisterTbl = ",
              "    TOPN(1, PlayersByAssists, [@Assists], DESC)",
              "VAR vTopAssisterKey = ",
              "    IF(COUNTROWS(TopAssisterTbl) > 0, MAXX(TopAssisterTbl, FactPlayerSeason[PlayerKey]), BLANK())",
              "VAR vTopAssisterName = ",
              "    IF(",
              "        NOT ISBLANK(vTopAssisterKey),",
              "        CALCULATE(MAX(DimPlayer[FullName]), DimPlayer[PlayerKey] = vTopAssisterKey),",
              "        \"–\"",
              "    )",
              "VAR vTopAssisterAssists = ",
              "    IF(",
              "        NOT ISBLANK(vTopAssisterKey),",
              "        CALCULATE(SUM(FactPlayerSeason[Assists]), FactPlayerSeason[PlayerKey] = vTopAssisterKey),",
              "        0",
              "    )",
              "",
              "-- Optional: If same player leads in both, show second-best assister for variety",
              "-- Comment out this section if you want to show the actual top assister even if same as scorer",
              "VAR vIsSamePlayer = (vTopScorerKey = vTopAssisterKey) && NOT ISBLANK(vTopScorerKey)",
              "VAR vSecondAssisterKey = ",
              "    IF(",
              "        vIsSamePlayer,",
              "        VAR FilteredPlayers = ",
              "            FILTER(",
              "                VALUES(FactPlayerSeason[PlayerKey]),",
              "                FactPlayerSeason[PlayerKey] <> vTopScorerKey",
              "            )",
              "        VAR PlayersWithAssists = ",
              "            ADDCOLUMNS(",
              "                FilteredPlayers,",
              "                \"@Assists\", CALCULATE(SUM(FactPlayerSeason[Assists]))",
              "            )",
              "        VAR SecondBest = TOPN(1, PlayersWithAssists, [@Assists], DESC)",
              "        RETURN",
              "            IF(COUNTROWS(SecondBest) > 0, MAXX(SecondBest, FactPlayerSeason[PlayerKey]), BLANK()),",
              "        vTopAssisterKey",
              "    )",
              "VAR vFinalAssisterKey = IF(ISBLANK(vSecondAssisterKey), vTopAssisterKey, vSecondAssisterKey)",
              "VAR vFinalAssisterName = ",
              "    IF(",
              "        NOT ISBLANK(vFinalAssisterKey),",
              "        CALCULATE(MAX(DimPlayer[FullName]), DimPlayer[PlayerKey] = vFinalAssisterKey),",
              "        IF(vIsSamePlayer, vTopScorerName, \"–\")",
              "    )",
              "VAR vFinalAssisterAssists = ",
              "    IF(",
              "        NOT ISBLANK(vFinalAssisterKey),",
              "        CALCULATE(SUM(FactPlayerSeason[Assists]), FactPlayerSeason[PlayerKey] = vFinalAssisterKey),",
              "        IF(vIsSamePlayer, CALCULATE(SUM(FactPlayerSeason[Assists]), FactPlayerSeason[PlayerKey] = vTopScorerKey), 0)",
              "    )",
              "",
              "-- Format values",
              "VAR vScorerGoalsFmt = ",
              "    IF(",
              "        ISBLANK(vTopScorerGoals) || vTopScorerGoals = 0,",
              "        \"0\",",
              "        FORMAT(vTopScorerGoals, \"#,0\")",
              "    )",
              "VAR vAssisterAssistsFmt = ",
              "    IF(",
              "        ISBLANK(vFinalAssisterAssists) || vFinalAssisterAssists = 0,",
              "        \"0\",",
              "        FORMAT(vFinalAssisterAssists, \"#,0\")",
              "    )",
              "",
              "-- Truncate long names (max 20 chars)",
              "VAR vScorerNameDisplay = ",
              "    IF(",
              "        LEN(vTopScorerName) > 20,",
              "        LEFT(vTopScorerName, 17) & \"...\",",
              "        vTopScorerName",
              "    )",
              "VAR vAssisterNameDisplay = ",
              "    IF(",
              "        LEN(vFinalAssisterName) > 20,",
              "        LEFT(vFinalAssisterName, 17) & \"...\",",
              "        vFinalAssisterName",
              "    )",
              "",
              "RETURN",
              "\"",
              "<style>",
              "  * { box-sizing: border-box; }",
              "  body {",
              "    margin: 0;",
              "    padding: 10px;",
              "    font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;",
              "    background: transparent;",
              "  }",
              "  .top-players-widget {",
              "    display: flex;",
              "    flex-direction: column;",
              "    gap: 8px;",
              "  }",
              "  .top-players-title {",
              "    font-size: 12px;",
              "    font-weight: 600;",
              "    color: #1a1a1a;",
              "    text-align: center;",
              "    margin-bottom: 2px;",
              "  }",
              "  .top-players-cards {",
              "    display: flex;",
              "    flex-wrap: wrap;",
              "    gap: 6px;",
              "    justify-content: center;",
              "  }",
              "  .player-card {",
              "    flex: 1 1 90px;",
              "    min-width: 70px;",
              "    max-width: 110px;",
              "    padding: 10px 8px;",
              "    border-radius: 8px;",
              "    text-align: center;",
              "    box-shadow: 0 2px 6px rgba(0,0,0,0.1);",
              "    transition: transform 0.2s ease;",
              "  }",
              "  .player-card:hover {",
              "    transform: translateY(-2px);",
              "    box-shadow: 0 4px 8px rgba(0,0,0,0.15);",
              "  }",
              "  .scorer-card {",
              "    background: linear-gradient(135deg, #FFFFFF 0%, #FFF3E0 100%);",
              "    border-left: 4px solid #E65C00;",
              "  }",
              "  .assister-card {",
              "    background: linear-gradient(135deg, #E8F4FC 0%, #D0E8F7 100%);",
              "    border-left: 4px solid #0066CC;",
              "  }",
              "  .player-icon {",
              "    width: 20px;",
              "    height: 20px;",
              "    margin: 0 auto 3px;",
              "    color: #404040;",
              "  }",
              "  .player-name {",
              "    font-size: 8px;",
              "    font-weight: 600;",
              "    color: #1a1a1a;",
              "    margin-bottom: 2px;",
              "    line-height: 1.2;",
              "    word-wrap: break-word;",
              "  }",
              "  .player-stat {",
              "    font-size: 18px;",
              "    font-weight: 700;",
              "    color: #1a1a1a;",
              "    margin-bottom: 1px;",
              "  }",
              "  .player-label {",
              "    font-size: 8px;",
              "    color: #404040;",
              "    text-transform: uppercase;",
              "    letter-spacing: 0.5px;",
              "  }",
              "</style>",
              "<div class='top-players-widget'>",
              "  <div class='top-players-title'>Top Performers</div>",
              "  <div class='top-players-cards'>",
              "    <div class='player-card scorer-card'>",
              "      <svg class='player-icon' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>",
              "        <circle cx='12' cy='8' r='4'/>",
              "        <path d='M4 20c1.5-3.5 4-5.5 8-5.5s6.5 2 8 5.5' stroke-linecap='round'/>",
              "        <circle cx='12' cy='12' r='8' stroke-dasharray='2 2' opacity='0.3'/>",
              "      </svg>",
              "      <div class='player-name'>\" & vScorerNameDisplay & \"</div>",
              "      <div class='player-stat'>\" & vScorerGoalsFmt & \"</div>",
              "      <div class='player-label'>Goals</div>",
              "    </div>",
              "    <div class='player-card assister-card'>",
              "      <svg class='player-icon' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>",
              "        <circle cx='12' cy='8' r='4'/>",
              "        <path d='M4 20c1.5-3.5 4-5.5 8-5.5s6.5 2 8 5.5' stroke-linecap='round'/>",
              "        <path d='M8 12l2 2 4-4' stroke-linecap='round' stroke-linejoin='round'/>",
              "      </svg>",
              "      <div class='player-name'>\" & vAssisterNameDisplay & \"</div>",
              "      <div class='player-stat'>\" & vAssisterAssistsFmt & \"</div>",
              "      <div class='player-label'>Assists</div>",
              "    </div>",
              "  </div>",
              "</div>",
              "\""
            ],
            "lineageTag": "e167b394-6f9e-4f35-8548-2e846c2853f3"
          },
          {
            "name": "Total Points",
            "expression": "SUM(FactClubMatch[Points])",
            "formatString": "0",
            "lineageTag": "ce4350fa-576f-402b-8136-a4be2d934dc2"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FactPlayerSeason",
        "lineageTag": "e93938bc-593c-47a9-a716-073dd9d992a7",
        "columns": [
          {
            "name": "PlayerKey",
            "dataType": "int64",
            "sourceColumn": "PlayerKey",
            "formatString": "0",
            "lineageTag": "6badec3f-8188-4a52-8172-a92f057192da",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ClubKey",
            "dataType": "int64",
            "sourceColumn": "ClubKey",
            "formatString": "0",
            "lineageTag": "82a789f0-c55b-489d-b105-4ba175f66b02",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Goals",
            "dataType": "int64",
            "sourceColumn": "Goals",
            "formatString": "0",
            "lineageTag": "b05eafab-162a-4a11-86f8-ba0d329f8d90",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Assists",
            "dataType": "int64",
            "sourceColumn": "Assists",
            "formatString": "0",
            "lineageTag": "4fd7e657-94fb-4668-93a6-0b7c6304b44d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MinutesPlayed",
            "dataType": "int64",
            "sourceColumn": "MinutesPlayed",
            "formatString": "0",
            "lineageTag": "610a0c9e-1c5f-4329-8499-125056b870d6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MatchesPlayed",
            "dataType": "int64",
            "sourceColumn": "MatchesPlayed",
            "formatString": "0",
            "lineageTag": "69adbdb3-c5a4-4614-9f3c-3ea379ab9199",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MatchesMissed",
            "dataType": "string",
            "sourceColumn": "MatchesMissed",
            "lineageTag": "ca00d6f2-a35e-43b7-9413-2be7a6a64101",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Starts",
            "dataType": "int64",
            "sourceColumn": "Starts",
            "formatString": "0",
            "lineageTag": "07cf16db-8865-402d-8beb-f00b0873bfb8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "YellowCards",
            "dataType": "int64",
            "sourceColumn": "YellowCards",
            "formatString": "0",
            "lineageTag": "37845169-fc4d-40ac-9db9-33a057de0c5e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RedCards",
            "dataType": "int64",
            "sourceColumn": "RedCards",
            "formatString": "0",
            "lineageTag": "d58b3f81-0795-45a3-b975-aeadb5570644",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Shots",
            "dataType": "int64",
            "sourceColumn": "Shots",
            "formatString": "0",
            "lineageTag": "12638e5e-33c9-4df4-a91e-c7b7ed0cc916",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ShotsOnTarget",
            "dataType": "int64",
            "sourceColumn": "ShotsOnTarget",
            "formatString": "0",
            "lineageTag": "00d3757d-9256-40a3-a3a3-3055cbf94898",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CleanSheets",
            "dataType": "int64",
            "sourceColumn": "CleanSheets",
            "formatString": "0",
            "lineageTag": "c26f8321-b996-437c-b959-78c18daa4a4f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Saves",
            "dataType": "int64",
            "sourceColumn": "Saves",
            "formatString": "0",
            "lineageTag": "1ba57390-524a-46aa-8287-0b31223251cc",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SuccessfulDribbles",
            "dataType": "int64",
            "sourceColumn": "SuccessfulDribbles",
            "formatString": "0",
            "lineageTag": "462c828a-8610-4f5d-a406-2f609299ca67",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Interceptions",
            "dataType": "int64",
            "sourceColumn": "Interceptions",
            "formatString": "0",
            "lineageTag": "9fc0140c-92da-4f3f-b460-af8bfdbcd26a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SuccessfulTackles",
            "dataType": "int64",
            "sourceColumn": "SuccessfulTackles",
            "formatString": "0",
            "lineageTag": "607427eb-6949-4296-a8c5-bf171027e2fa",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactPlayerSeason",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Staging_PlayerStats,",
                "    #\"Requêtes fusionnées\" = Table.NestedJoin(Source, {\"club\"}, DimClub, {\"ClubName\"}, \"DimClub\", JoinKind.LeftOuter),",
                "    #\"DimClub développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées\", \"DimClub\", {\"ClubKey\"}, {\"DimClub.ClubKey\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"DimClub développé\",{{\"DimClub.ClubKey\", \"ClubKey\"}}),",
                "    #\"Requêtes fusionnées1\" = Table.NestedJoin(#\"Colonnes renommées\", {\"player_id\"}, DimPlayer, {\"PlayerId\"}, \"DimPlayer\", JoinKind.LeftOuter),",
                "    #\"DimPlayer développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées1\", \"DimPlayer\", {\"PlayerKey\"}, {\"DimPlayer.PlayerKey\"}),",
                "    #\"Colonnes renommées1\" = Table.RenameColumns(#\"DimPlayer développé\",{{\"DimPlayer.PlayerKey\", \"PlayerKey\"}}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Colonnes renommées1\", \"MatchesMissed\", each 38 - [matches_played]),",
                "    #\"Colonnes permutées\" = Table.ReorderColumns(#\"Personnalisée ajoutée\",{\"PlayerKey\", \"player_id\", \"ClubKey\", \"full_name\", \"club\", \"position\", \"matches_played\", \"starts\", \"goals\", \"minutes_played\", \"assists\", \"yellow_cards\", \"red_cards\", \"shots\", \"shots_on_target\", \"clean_sheets\", \"saves\", \"successful_dribbles\", \"interceptions\", \"successful_tackles\", \"MatchesMissed\"}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Colonnes permutées\",{\"player_id\", \"full_name\", \"club\", \"position\"}),",
                "    #\"Colonnes permutées1\" = Table.ReorderColumns(#\"Colonnes supprimées\",{\"PlayerKey\", \"ClubKey\", \"goals\", \"matches_played\", \"starts\", \"minutes_played\", \"assists\", \"yellow_cards\", \"red_cards\", \"shots\", \"shots_on_target\", \"clean_sheets\", \"saves\", \"successful_dribbles\", \"interceptions\", \"successful_tackles\", \"MatchesMissed\"}),",
                "    #\"Colonnes renommées2\" = Table.RenameColumns(#\"Colonnes permutées1\",{{\"goals\", \"Goals\"}}),",
                "    #\"Colonnes permutées2\" = Table.ReorderColumns(#\"Colonnes renommées2\",{\"PlayerKey\", \"ClubKey\", \"Goals\", \"assists\", \"matches_played\", \"starts\", \"minutes_played\", \"yellow_cards\", \"red_cards\", \"shots\", \"shots_on_target\", \"clean_sheets\", \"saves\", \"successful_dribbles\", \"interceptions\", \"successful_tackles\", \"MatchesMissed\"}),",
                "    #\"Colonnes renommées3\" = Table.RenameColumns(#\"Colonnes permutées2\",{{\"assists\", \"Assists\"}, {\"minutes_played\", \"MinutesPlayed\"}}),",
                "    #\"Colonnes permutées3\" = Table.ReorderColumns(#\"Colonnes renommées3\",{\"PlayerKey\", \"ClubKey\", \"Goals\", \"Assists\", \"MinutesPlayed\", \"matches_played\", \"starts\", \"yellow_cards\", \"red_cards\", \"shots\", \"shots_on_target\", \"clean_sheets\", \"saves\", \"successful_dribbles\", \"interceptions\", \"successful_tackles\", \"MatchesMissed\"}),",
                "    #\"Colonnes renommées4\" = Table.RenameColumns(#\"Colonnes permutées3\",{{\"matches_played\", \"MatchesPlayed\"}}),",
                "    #\"Colonnes permutées4\" = Table.ReorderColumns(#\"Colonnes renommées4\",{\"PlayerKey\", \"ClubKey\", \"Goals\", \"Assists\", \"MinutesPlayed\", \"MatchesPlayed\", \"MatchesMissed\", \"starts\", \"yellow_cards\", \"red_cards\", \"shots\", \"shots_on_target\", \"clean_sheets\", \"saves\", \"successful_dribbles\", \"interceptions\", \"successful_tackles\"}),",
                "    #\"Colonnes renommées5\" = Table.RenameColumns(#\"Colonnes permutées4\",{{\"starts\", \"Starts\"}, {\"yellow_cards\", \"YellowCards\"}, {\"red_cards\", \"RedCards\"}, {\"shots\", \"Shots\"}, {\"shots_on_target\", \"ShotsOnTarget\"}, {\"clean_sheets\", \"CleanSheets\"}, {\"saves\", \"Saves\"}, {\"successful_dribbles\", \"SuccessfulDribbles\"}, {\"interceptions\", \"Interceptions\"}, {\"successful_tackles\", \"SuccessfulTackles\"}})",
                "in",
                "    #\"Colonnes renommées5\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Average Age",
            "expression": "AVERAGE(DimPlayer[Age])",
            "lineageTag": "63c0b9d1-b56d-4bac-83fa-fefda4d39e72",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Average Minutes",
            "expression": "AVERAGE(FactPlayerSeason[MinutesPlayed])",
            "lineageTag": "68c1a3b3-f1c0-40d3-ab68-11ab2cdba3f0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Contribution HTML",
            "expression": [
              "",
              "VAR vTeamGoals = SUM(FactPlayerSeason[Goals])",
              "VAR vTeamAssists = SUM(FactPlayerSeason[Assists])",
              "VAR vTeamTotal = vTeamGoals + vTeamAssists",
              "",
              "VAR vTop5Goals = ",
              "    CALCULATE(",
              "        SUM(FactPlayerSeason[Goals]),",
              "        TOPN(5, VALUES(FactPlayerSeason[PlayerKey]), CALCULATE(SUM(FactPlayerSeason[Goals])), DESC)",
              "    )",
              "VAR vTop5Assists = ",
              "    CALCULATE(",
              "        SUM(FactPlayerSeason[Assists]),",
              "        TOPN(5, VALUES(FactPlayerSeason[PlayerKey]), CALCULATE(SUM(FactPlayerSeason[Assists])), DESC)",
              "    )",
              "VAR vTop5Total = vTop5Goals + vTop5Assists",
              "VAR vTop5Pct = IF(vTeamTotal > 0, DIVIDE(vTop5Total, vTeamTotal, 0), 0)",
              "",
              "VAR vTop10Goals = ",
              "    CALCULATE(",
              "        SUM(FactPlayerSeason[Goals]),",
              "        TOPN(10, VALUES(FactPlayerSeason[PlayerKey]), CALCULATE(SUM(FactPlayerSeason[Goals])), DESC)",
              "    )",
              "VAR vTop10Assists = ",
              "    CALCULATE(",
              "        SUM(FactPlayerSeason[Assists]),",
              "        TOPN(10, VALUES(FactPlayerSeason[PlayerKey]), CALCULATE(SUM(FactPlayerSeason[Assists])), DESC)",
              "    )",
              "VAR vTop10Total = vTop10Goals + vTop10Assists",
              "VAR vTop10Pct = IF(vTeamTotal > 0, DIVIDE(vTop10Total, vTeamTotal, 0), 0)",
              "",
              "VAR vTop5Fmt = IF(ISBLANK(vTop5Pct), \"0%\", FORMAT(vTop5Pct, \"0%\"))",
              "VAR vTop10Fmt = IF(ISBLANK(vTop10Pct), \"0%\", FORMAT(vTop10Pct, \"0%\"))",
              "",
              "RETURN",
              "\"",
              "<style>",
              "  * { box-sizing: border-box; }",
              "  body { margin: 0; padding: 16px; font-family: 'Segoe UI', sans-serif; background: transparent; }",
              "  .contrib-widget { display: flex; flex-direction: column; gap: 12px; }",
              "  .contrib-title { font-size: 14px; font-weight: 600; color: #333; text-align: center; margin-bottom: 4px; }",
              "  .contrib-cards { display: flex; flex-wrap: wrap; gap: 10px; justify-content: center; }",
              "  .contrib-card { flex: 1 1 100px; min-width: 80px; max-width: 120px; padding: 14px 10px; border-radius: 10px; text-align: center; box-shadow: 0 2px 6px rgba(0,0,0,0.15); transition: transform 0.2s ease; }",
              "  .contrib-card:hover { transform: translateY(-2px); box-shadow: 0 4px 8px rgba(0,0,0,0.2); }",
              "  .contrib-card.top5 { background: linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%); border-left: 4px solid #2e7d32; }",
              "  .contrib-card.top10 { background: linear-gradient(135deg, #e3f2fd 0%, #bbdefb 100%); border-left: 4px solid #1565c0; }",
              "  .contrib-value { font-size: 22px; font-weight: 700; color: #111; margin-bottom: 4px; }",
              "  .contrib-label { font-size: 11px; color: #555; text-transform: uppercase; letter-spacing: 0.5px; }",
              "</style>",
              "<div class='contrib-widget'>",
              "  <div class='contrib-title'>Top Players Contribution</div>",
              "  <div class='contrib-cards'>",
              "    <div class='contrib-card top5'><div class='contrib-value'>\" & vTop5Fmt & \"</div><div class='contrib-label'>Top 5 (G+A)</div></div>",
              "    <div class='contrib-card top10'><div class='contrib-value'>\" & vTop10Fmt & \"</div><div class='contrib-label'>Top 10 (G+A)</div></div>",
              "  </div>",
              "</div>",
              "\""
            ],
            "lineageTag": "f068da41-25e7-437a-a590-3e4528a563e9"
          },
          {
            "name": "Goals + Assists",
            "expression": "[Total Goals] + [Total Assists]",
            "lineageTag": "e51a2d00-770b-459c-a953-e3cb936f99f0"
          },
          {
            "name": "Performance Score",
            "expression": [
              "",
              "VAR Pos = SELECTEDVALUE(DimPlayer[Position])",
              "VAR G   = SUM(FactPlayerSeason[Goals])",
              "VAR A   = SUM(FactPlayerSeason[Assists])",
              "VAR Sh  = SUM(FactPlayerSeason[Shots])",
              "VAR SoT = SUM(FactPlayerSeason[ShotsOnTarget])",
              "VAR Dr  = SUM(FactPlayerSeason[SuccessfulDribbles])",
              "VAR Int = SUM(FactPlayerSeason[Interceptions])",
              "VAR Tck = SUM(FactPlayerSeason[SuccessfulTackles])",
              "VAR CS  = SUM(FactPlayerSeason[CleanSheets])",
              "VAR Sav = SUM(FactPlayerSeason[Saves])",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    -- Goalkeeper (1 position)",
              "    Pos = \"Goalkeeper\", (CS * 3) + (Sav / 10),",
              "",
              "    -- Defenders (3): Left back, Right back, Center back",
              "    Pos = \"Left back\",     (Int / 2) + (Tck / 2) + (G * 5) + (A * 3),",
              "    Pos = \"Right back\",    (Int / 2) + (Tck / 2) + (G * 5) + (A * 3),",
              "    Pos = \"Center back\",   (Int / 2) + (Tck / 2) + (G * 5) + (A * 3),",
              "",
              "    -- Midfielders (3): Defensive, Central, Attacking",
              "    Pos = \"Defensive midfielder\", (G * 5) + (A * 3) + (Dr / 5) + (Int / 3) + (Tck / 3),",
              "    Pos = \"Central midfielder\",   (G * 5) + (A * 3) + (Dr / 5) + (Int / 3) + (Tck / 3),",
              "    Pos = \"Attacking midfielder\", (G * 5) + (A * 3) + (Dr / 5) + (Int / 3) + (Tck / 3),",
              "",
              "    -- Forwards / wingers (3): Left winger, Right winger, Forward",
              "    Pos = \"Left winger\",  (G * 5) + (A * 3) + (SoT / 5),",
              "    Pos = \"Right winger\", (G * 5) + (A * 3) + (SoT / 5),",
              "    Pos = \"Forward\",      (G * 5) + (A * 3) + (SoT / 5),",
              "",
              "    -- Fallback (unknown or new position in model)",
              "    (G * 5) + (A * 3)",
              ")"
            ],
            "lineageTag": "c1bd1f89-0de6-44ca-975b-86a0dff986df",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Player Count",
            "expression": "COUNTROWS(DimPlayer)",
            "formatString": "0",
            "lineageTag": "a768b235-a803-4714-83af-eb14e4ba8f06"
          },
          {
            "name": "Players in Bin",
            "expression": [
              "",
              "VAR BinSort = SELECTEDVALUE(MinutesBins[Bin Sort])",
              "VAR Low =",
              "    SWITCH(BinSort, 1, 0, 2, 500, 3, 1000, 4, 1500, 5, 2000, 6, 2500, 7, 3000, 0)",
              "VAR High =",
              "    SWITCH(BinSort, 1, 500, 2, 1000, 3, 1500, 4, 2000, 5, 2500, 6, 3000, 7, 999999, 0)",
              "VAR vTbl =",
              "    FILTER(",
              "        ADDCOLUMNS(VALUES(DimPlayer[PlayerKey]), \"@M\", [Total Minutes]),",
              "        [@M] >= Low && [@M] < High",
              "    )",
              "RETURN",
              "COUNTROWS(vTbl)"
            ],
            "lineageTag": "2dff86e0-c6af-488f-bc78-b573a4d71414"
          },
          {
            "name": "Squad Summary HTML",
            "expression": [
              "",
              "VAR vPlayers = COUNTROWS(FactPlayerSeason)",
              "VAR vGoals = SUM(FactPlayerSeason[Goals])",
              "VAR vAssists = SUM(FactPlayerSeason[Assists])",
              "VAR vAvgAge = AVERAGE(DimPlayer[Age])",
              "",
              "VAR vGoalsFmt = IF(ISBLANK(vGoals) || vGoals = 0, \"0\", FORMAT(vGoals, \"#,0\"))",
              "VAR vAssistsFmt = IF(ISBLANK(vAssists) || vAssists = 0, \"0\", FORMAT(vAssists, \"#,0\"))",
              "VAR vAgeFmt = IF(ISBLANK(vAvgAge), \"–\", FORMAT(vAvgAge, \"0.0\"))",
              "VAR vPlayersFmt = IF(ISBLANK(vPlayers) || vPlayers = 0, \"0\", FORMAT(vPlayers, \"#,0\"))",
              "",
              "RETURN",
              "\"",
              "<style>",
              "  * { box-sizing: border-box; }",
              "  body { margin: 0; padding: 16px; font-family: 'Segoe UI', sans-serif; background: transparent; }",
              "  .squad-summary-widget { display: flex; flex-direction: column; gap: 12px; }",
              "  .squad-summary-title { font-size: 14px; font-weight: 600; color: #333; text-align: center; margin-bottom: 4px; }",
              "  .squad-summary-cards { display: flex; flex-wrap: wrap; gap: 10px; justify-content: center; }",
              "  .squad-card { flex: 1 1 100px; min-width: 80px; max-width: 120px; padding: 14px 10px; border-radius: 10px; text-align: center; box-shadow: 0 2px 6px rgba(0,0,0,0.15); transition: transform 0.2s ease; }",
              "  .squad-card:hover { transform: translateY(-2px); box-shadow: 0 4px 8px rgba(0,0,0,0.2); }",
              "  .squad-card.c1 { background: linear-gradient(135deg, #e3f2fd 0%, #bbdefb 100%); border-left: 4px solid #1976d2; }",
              "  .squad-card.c2 { background: linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%); border-left: 4px solid #388e3c; }",
              "  .squad-card.c3 { background: linear-gradient(135deg, #fff3e0 0%, #ffe0b2 100%); border-left: 4px solid #f57c00; }",
              "  .squad-card.c4 { background: linear-gradient(135deg, #fce4ec 0%, #f8bbd9 100%); border-left: 4px solid #c2185b; }",
              "  .squad-card-value { font-size: 22px; font-weight: 700; color: #111; margin-bottom: 4px; }",
              "  .squad-card-label { font-size: 11px; color: #555; text-transform: uppercase; letter-spacing: 0.5px; }",
              "</style>",
              "<div class='squad-summary-widget'>",
              "  <div class='squad-summary-title'>Squad Summary</div>",
              "  <div class='squad-summary-cards'>",
              "    <div class='squad-card c1'><div class='squad-card-value'>\" & vPlayersFmt & \"</div><div class='squad-card-label'>Players</div></div>",
              "    <div class='squad-card c2'><div class='squad-card-value'>\" & vGoalsFmt & \"</div><div class='squad-card-label'>Goals</div></div>",
              "    <div class='squad-card c3'><div class='squad-card-value'>\" & vAssistsFmt & \"</div><div class='squad-card-label'>Assists</div></div>",
              "    <div class='squad-card c4'><div class='squad-card-value'>\" & vAgeFmt & \"</div><div class='squad-card-label'>Avg Age</div></div>",
              "  </div>",
              "</div>",
              "\""
            ],
            "lineageTag": "b571488d-12fa-4391-84ca-474fdb76c3c5"
          },
          {
            "name": "Total Assists",
            "expression": "SUM(FactPlayerSeason[Assists])",
            "formatString": "0",
            "lineageTag": "7175a530-f15a-43ff-b57c-472ef61a5515"
          },
          {
            "name": "Total Goals",
            "expression": "SUM(FactPlayerSeason[Goals])",
            "formatString": "0",
            "lineageTag": "f5da58e9-3a5a-459d-8469-232a1d9c0d28"
          },
          {
            "name": "Total Minutes",
            "expression": "SUM(FactPlayerSeason[MinutesPlayed])",
            "formatString": "0",
            "lineageTag": "beacdab3-2ce0-4af6-b389-36efd5084bfd"
          },
          {
            "name": "Avg Goals Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE ( FactPlayerSeason[Goals] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "lineageTag": "708d3ba5-1704-47bd-a793-b1e4af60a6bb",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Min Goals Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( FactPlayerSeason[Goals] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "9687e8a8-b0e0-4636-9ec8-829228e3299a"
          },
          {
            "name": "Max Goals Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( FactPlayerSeason[Goals] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3f549bf1-7929-45ea-bed3-a95c68176ada"
          },
          {
            "name": "Avg Interceptions Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE ( FactPlayerSeason[Interceptions] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "lineageTag": "3c00f9df-16d1-4a25-ae69-a0e88fe44bc0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Max Interceptions Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( FactPlayerSeason[Interceptions] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "49b77bfe-c1d9-4492-94f2-2247962d2b45"
          },
          {
            "name": "Min Interceptions Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( FactPlayerSeason[Interceptions] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c6251712-53de-4d88-802f-8f2b2cd6eae6"
          },
          {
            "name": "Total Interceptions",
            "expression": "SUM(FactPlayerSeason[Interceptions])",
            "formatString": "0",
            "lineageTag": "314d8d22-5bb1-469b-93f4-c09a88c9e808"
          },
          {
            "name": "Avg RedCards Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE ( FactPlayerSeason[RedCards] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "lineageTag": "20f835bd-01cd-4a6c-a10f-64a7d56cfb00",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Saves Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE ( FactPlayerSeason[Saves] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "lineageTag": "f315beee-785b-4726-bb1d-59dcb79cb873",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Shots Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE ( FactPlayerSeason[Shots] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "lineageTag": "bbeee529-cee1-4074-9888-6b5978dc1590",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg ShotsOnTarget Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE ( FactPlayerSeason[ShotsOnTarget] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "lineageTag": "5447a6d8-4eef-4355-8fb1-b8e2ac8e2df5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg SuccessfulDribbles Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE ( FactPlayerSeason[SuccessfulDribbles] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "lineageTag": "3aa0c155-ba8f-40fd-ba19-8c10241fe6b9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg SuccessfulTackles Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE ( FactPlayerSeason[SuccessfulTackles] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "lineageTag": "21843d27-df9a-4c34-82f3-9ef9bcd14650",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Max RedCards Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( FactPlayerSeason[RedCards] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f97596b6-9666-4b3c-98b6-1a4c7a692242"
          },
          {
            "name": "Max Saves Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( FactPlayerSeason[Saves] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "05fc5d3c-9912-4f17-bf13-e7536bcb1941"
          },
          {
            "name": "Max Shots Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( FactPlayerSeason[Shots] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ed5f6de7-5b48-4b2f-a2ab-636178b9427e"
          },
          {
            "name": "Max ShotsOnTarget Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( FactPlayerSeason[ShotsOnTarget] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "82a014c0-599f-4c0d-8c0a-7194eee5920e"
          },
          {
            "name": "Max SuccessfulDribbles Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( FactPlayerSeason[SuccessfulDribbles] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "65d48b5b-9192-4871-ae6e-de7aa02177c2"
          },
          {
            "name": "Max SuccessfulTackles Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( FactPlayerSeason[SuccessfulTackles] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5aca2596-8fdb-44f7-80fe-a11192e5eba7"
          },
          {
            "name": "Min RedCards Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( FactPlayerSeason[RedCards] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "8ef53803-f2b6-405d-8be8-74002ba05490"
          },
          {
            "name": "Min Saves Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( FactPlayerSeason[Saves] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1aaeffd9-f304-43bd-98ab-88e027d924de"
          },
          {
            "name": "Min Shots Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( FactPlayerSeason[Goals] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "82a5f563-de6a-470d-bee2-b437eeb1e793"
          },
          {
            "name": "Min ShotsOnTarget Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( FactPlayerSeason[ShotsOnTarget] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "50187ba5-020a-4206-b970-153c8d7fa4e7"
          },
          {
            "name": "Min SuccessfulDribbles Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( FactPlayerSeason[SuccessfulDribbles] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b817db37-ef1d-4192-89c0-0a37c8388e35"
          },
          {
            "name": "Min SuccessfulTackles Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( FactPlayerSeason[SuccessfulTackles] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b4817c2d-c5b3-467d-843a-e5e8231b3367"
          },
          {
            "name": "Total RedCards",
            "expression": "SUM(FactPlayerSeason[RedCards])",
            "formatString": "0",
            "lineageTag": "6cc27e76-a203-48db-b174-f8370663de0c"
          },
          {
            "name": "Total Saves",
            "expression": "SUM(FactPlayerSeason[Saves])",
            "formatString": "0",
            "lineageTag": "ef6b1f9c-5ab8-46de-a6cf-21610968992d"
          },
          {
            "name": "Total Shots",
            "expression": "SUM(FactPlayerSeason[Shots])",
            "formatString": "0",
            "lineageTag": "d33450e4-a740-4c34-a8c6-86196d632d81"
          },
          {
            "name": "Total ShotsOnTarget",
            "expression": "SUM(FactPlayerSeason[ShotsOnTarget])",
            "formatString": "0",
            "lineageTag": "839ec182-9840-4a03-814d-7f018d7bc4a3"
          },
          {
            "name": "Total SuccessfulDribbles",
            "expression": "SUM(FactPlayerSeason[SuccessfulDribbles])",
            "formatString": "0",
            "lineageTag": "9fd9a464-c0d5-421a-98bd-8e6eec999fba"
          },
          {
            "name": "Mesure",
            "lineageTag": "57c3e753-d86e-4c14-b2cd-774038460801",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ]
          },
          {
            "name": "Total SuccessfulTackles",
            "expression": "SUM(FactPlayerSeason[SuccessfulTackles])",
            "formatString": "0",
            "lineageTag": "63fc2373-cd97-4113-9371-14db20d09bdc"
          },
          {
            "name": "Avg Assists Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE ( FactPlayerSeason[Assists] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "lineageTag": "b4fa35bf-f940-4717-a190-c4661c45ae59",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Max Assists Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MAX ( FactPlayerSeason[Assists] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "13257f18-e0fa-4e11-b410-6759d22d784c"
          },
          {
            "name": "Min Assists Same Position",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( FactPlayerSeason[Assists] ),",
              "    ALLEXCEPT ( DimPlayer, DimPlayer[Position] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1bc3d5f9-3dda-4dfb-a252-ea2b131af30c"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FactTransfer",
        "lineageTag": "887562a7-d105-4bd7-a8a3-5eb01c9fa098",
        "columns": [
          {
            "name": "TransferKey",
            "dataType": "string",
            "sourceColumn": "TransferKey",
            "lineageTag": "21e31c17-21fe-4b89-9cee-e9deee5c4b84",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PlayerKey",
            "dataType": "int64",
            "sourceColumn": "PlayerKey",
            "formatString": "0",
            "lineageTag": "dbc618df-f443-45d8-a4bb-0b6d3a5d565e",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DepartureClubKey",
            "dataType": "int64",
            "sourceColumn": "DepartureClubKey",
            "formatString": "0",
            "lineageTag": "1bad0eed-91b0-40f1-8a50-4a876e67f941",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ArrivalClubKey",
            "dataType": "int64",
            "sourceColumn": "ArrivalClubKey",
            "formatString": "0",
            "lineageTag": "2f05045c-b3f3-4a43-88ae-e56b2f5e02e8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TransferDateKey",
            "dataType": "string",
            "sourceColumn": "TransferDateKey",
            "lineageTag": "3330609b-563d-4bf6-a840-d0fd61481a64",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AmountME",
            "dataType": "double",
            "sourceColumn": "AmountME",
            "lineageTag": "3a9ad9ab-31b8-4b1b-a292-7dd198c5989a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "TransferType",
            "dataType": "string",
            "sourceColumn": "TransferType",
            "lineageTag": "393e722b-35d0-4c76-8432-88e4c4a0e1cd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Agent",
            "dataType": "string",
            "sourceColumn": "Agent",
            "lineageTag": "30ee75d3-40ec-470b-976f-029936045c82",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactTransfer",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Staging_Transfers,",
                "    #\"Requêtes fusionnées\" = Table.NestedJoin(Source, {\"player_id\"}, DimPlayer, {\"PlayerId\"}, \"DimPlayer\", JoinKind.LeftOuter),",
                "    #\"DimPlayer développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées\", \"DimPlayer\", {\"PlayerKey\"}, {\"DimPlayer.PlayerKey\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"DimPlayer développé\",{{\"DimPlayer.PlayerKey\", \"PlayerKey\"}}),",
                "    #\"Requêtes fusionnées1\" = Table.NestedJoin(#\"Colonnes renommées\", {\"departure_club\"}, DimClub, {\"ClubName\"}, \"DimClub\", JoinKind.LeftOuter),",
                "    #\"DimClub développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées1\", \"DimClub\", {\"ClubKey\"}, {\"DimClub.ClubKey\"}),",
                "    #\"Colonnes renommées1\" = Table.RenameColumns(#\"DimClub développé\",{{\"DimClub.ClubKey\", \"DepartureClubKey\"}}),",
                "    #\"Requêtes fusionnées2\" = Table.NestedJoin(#\"Colonnes renommées1\", {\"arrival_club\"}, DimClub, {\"ClubName\"}, \"DimClub\", JoinKind.LeftOuter),",
                "    #\"DimClub développé1\" = Table.ExpandTableColumn(#\"Requêtes fusionnées2\", \"DimClub\", {\"ClubKey\"}, {\"DimClub.ClubKey\"}),",
                "    #\"Colonnes renommées2\" = Table.RenameColumns(#\"DimClub développé1\",{{\"DimClub.ClubKey\", \"ArrivalClubKey\"}}),",
                "    #\"Requêtes fusionnées3\" = Table.NestedJoin(#\"Colonnes renommées2\", {\"transfer_date\"}, DimDate, {\"DateKey\"}, \"DimDate\", JoinKind.LeftOuter),",
                "    #\"DimDate développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées3\", \"DimDate\", {\"DateKey\"}, {\"DimDate.DateKey\"}),",
                "    #\"Colonnes renommées3\" = Table.RenameColumns(#\"DimDate développé\",{{\"DimDate.DateKey\", \"TransferDateKey\"}, {\"transfer_id\", \"TransferKey\"}}),",
                "    #\"Colonnes permutées\" = Table.ReorderColumns(#\"Colonnes renommées3\",{\"TransferKey\", \"PlayerKey\", \"player\", \"player_id\", \"departure_club\", \"arrival_club\", \"transfer_type\", \"amount_ME\", \"transfer_date\", \"agent\", \"DepartureClubKey\", \"ArrivalClubKey\", \"TransferDateKey\"}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Colonnes permutées\",{\"player\", \"player_id\", \"arrival_club\"}),",
                "    #\"Colonnes permutées1\" = Table.ReorderColumns(#\"Colonnes supprimées\",{\"TransferKey\", \"PlayerKey\", \"departure_club\", \"transfer_date\", \"DepartureClubKey\", \"ArrivalClubKey\", \"transfer_type\", \"amount_ME\", \"agent\", \"TransferDateKey\"}),",
                "    #\"Colonnes supprimées1\" = Table.RemoveColumns(#\"Colonnes permutées1\",{\"departure_club\", \"transfer_date\"}),",
                "    #\"Colonnes permutées2\" = Table.ReorderColumns(#\"Colonnes supprimées1\",{\"TransferKey\", \"PlayerKey\", \"DepartureClubKey\", \"ArrivalClubKey\", \"TransferDateKey\", \"transfer_type\", \"amount_ME\", \"agent\"}),",
                "    #\"Colonnes renommées4\" = Table.RenameColumns(#\"Colonnes permutées2\",{{\"amount_ME\", \"AmountME\"}}),",
                "    #\"Colonnes permutées3\" = Table.ReorderColumns(#\"Colonnes renommées4\",{\"TransferKey\", \"PlayerKey\", \"DepartureClubKey\", \"ArrivalClubKey\", \"TransferDateKey\", \"AmountME\", \"transfer_type\", \"agent\"}),",
                "    #\"Colonnes renommées6\" = Table.RenameColumns(#\"Colonnes permutées3\",{{\"transfer_type\", \"TransferType\"}, {\"agent\", \"Agent\"}})",
                "in",
                "    #\"Colonnes renommées6\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Transfer Amount (ME)",
            "expression": "SUM(FactTransfer[AmountME])",
            "lineageTag": "786021ca-eea8-48be-81d9-5a87f41d0c7b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FactSanction",
        "lineageTag": "65990b99-a3ac-4a73-bb34-beb5e4aae07d",
        "columns": [
          {
            "name": "SanctionKey",
            "dataType": "string",
            "sourceColumn": "SanctionKey",
            "lineageTag": "6d3139ca-c3a4-4cea-b645-16ca6fbf0e8a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PlayerKey",
            "dataType": "int64",
            "sourceColumn": "PlayerKey",
            "formatString": "0",
            "lineageTag": "1eef5657-b81f-4c33-8a9e-ac4f2a166559",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ClubKey",
            "dataType": "int64",
            "sourceColumn": "ClubKey",
            "formatString": "0",
            "lineageTag": "8a0e471b-6c33-4be9-ae4b-9bc7a8192d04",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SanctionDateKey",
            "dataType": "string",
            "sourceColumn": "SanctionDateKey",
            "lineageTag": "d381fbcf-3c4c-42b4-9292-39e65f2376c6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SanctionType",
            "dataType": "string",
            "sourceColumn": "SanctionType",
            "lineageTag": "08808230-c809-4cd8-95df-cb009d810531",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reason",
            "dataType": "string",
            "sourceColumn": "Reason",
            "lineageTag": "019cf59e-00bc-47f7-9ed2-ab98c5826812",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SuspensionMatches",
            "dataType": "int64",
            "sourceColumn": "SuspensionMatches",
            "formatString": "0",
            "lineageTag": "892b2da1-04bb-4b68-9a7b-e0eb993b845c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FineEuros",
            "dataType": "int64",
            "sourceColumn": "FineEuros",
            "formatString": "0",
            "lineageTag": "a35ac5c0-e9c0-473b-9f12-91f4acc7e492",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactSanction",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Staging_Sanctions,",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(Source,{\"player\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Colonnes supprimées\",{{\"sanction_id\", \"SanctionKey\"}}),",
                "    #\"Requêtes fusionnées\" = Table.NestedJoin(#\"Colonnes renommées\", {\"player_id\"}, DimPlayer, {\"PlayerId\"}, \"DimPlayer\", JoinKind.LeftOuter),",
                "    #\"DimPlayer développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées\", \"DimPlayer\", {\"PlayerKey\"}, {\"DimPlayer.PlayerKey\"}),",
                "    #\"Colonnes renommées1\" = Table.RenameColumns(#\"DimPlayer développé\",{{\"DimPlayer.PlayerKey\", \"PlayerKey\"}}),",
                "    #\"Colonnes permutées\" = Table.ReorderColumns(#\"Colonnes renommées1\",{\"SanctionKey\", \"PlayerKey\", \"player_id\", \"club\", \"sanction_date\", \"sanction_type\", \"reason\", \"suspension_matches\", \"fine_euros\"}),",
                "    #\"Colonnes supprimées1\" = Table.RemoveColumns(#\"Colonnes permutées\",{\"player_id\"}),",
                "    #\"Requêtes fusionnées1\" = Table.NestedJoin(#\"Colonnes supprimées1\", {\"club\"}, DimClub, {\"ClubName\"}, \"DimClub\", JoinKind.LeftOuter),",
                "    #\"DimClub développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées1\", \"DimClub\", {\"ClubKey\"}, {\"DimClub.ClubKey\"}),",
                "    #\"Colonnes renommées2\" = Table.RenameColumns(#\"DimClub développé\",{{\"DimClub.ClubKey\", \"ClubKey\"}}),",
                "    #\"Colonnes permutées1\" = Table.ReorderColumns(#\"Colonnes renommées2\",{\"SanctionKey\", \"PlayerKey\", \"ClubKey\", \"club\", \"sanction_date\", \"sanction_type\", \"reason\", \"suspension_matches\", \"fine_euros\"}),",
                "    #\"Colonnes supprimées2\" = Table.RemoveColumns(#\"Colonnes permutées1\",{\"club\"}),",
                "    #\"Requêtes fusionnées2\" = Table.NestedJoin(#\"Colonnes supprimées2\", {\"sanction_date\"}, DimDate, {\"DateKey\"}, \"DimDate\", JoinKind.LeftOuter),",
                "    #\"DimDate développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées2\", \"DimDate\", {\"DateKey\"}, {\"DimDate.DateKey\"}),",
                "    #\"Colonnes renommées3\" = Table.RenameColumns(#\"DimDate développé\",{{\"DimDate.DateKey\", \"SanctionDateKey\"}}),",
                "    #\"Colonnes permutées2\" = Table.ReorderColumns(#\"Colonnes renommées3\",{\"SanctionKey\", \"PlayerKey\", \"ClubKey\", \"SanctionDateKey\", \"sanction_date\", \"sanction_type\", \"reason\", \"suspension_matches\", \"fine_euros\"}),",
                "    #\"Colonnes supprimées3\" = Table.RemoveColumns(#\"Colonnes permutées2\",{\"sanction_date\"}),",
                "    #\"Colonnes renommées4\" = Table.RenameColumns(#\"Colonnes supprimées3\",{{\"sanction_type\", \"SanctionType\"}, {\"reason\", \"Reason\"}, {\"suspension_matches\", \"SuspensionMatches\"}, {\"fine_euros\", \"FineEuros\"}})",
                "in",
                "    #\"Colonnes renommées4\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sanction Count",
            "expression": "COUNTROWS(FactSanction)",
            "formatString": "0",
            "lineageTag": "190fb9e4-8ea6-46a6-9dcf-02d16c416c2c"
          },
          {
            "name": "Cumulative Sanction Count",
            "expression": [
              "",
              "VAR CurrentMatchday =",
              "    MAX ( DimMatch[Matchday] )",
              "VAR EndDate =",
              "    CALCULATE (",
              "        MAX ( DimMatch[DateKey] ),",
              "        REMOVEFILTERS ( DimMatch ),",
              "        DimMatch[Matchday] = CurrentMatchday",
              "    )",
              "RETURN",
              "    CALCULATE (",
              "        [Sanction Count],",
              "        REMOVEFILTERS ( DimMatch ),            -- clé: enlever le filtre de l’axe",
              "        FILTER (",
              "            ALL ( DimDate[DateKey] ),          -- cumul via la dimension date",
              "            DimDate[DateKey] <= EndDate",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "c881e647-aa50-4f83-abe8-ea01014b5533"
          },
          {
            "name": "Sanctions Domicile",
            "expression": [
              "",
              "SUMX(",
              "    FILTER(",
              "        FactSanction,",
              "        FactSanction[Reason] = \"Abusive language in mixed zone\"",
              "            || FactSanction[Reason] = \"Accumulation of yellow cards\"",
              "            || FactSanction[Reason] = \"Deliberate elbow strike\"",
              "            || FactSanction[Reason] = \"Inappropriate gesture towards an opponent\"",
              "            || FactSanction[Reason] = \"Insulting the referee\"",
              "            || FactSanction[Reason] = \"On-field brawl\"",
              "            || FactSanction[Reason] = \"Red card - last man foul\"",
              "            || FactSanction[Reason] = \"Repeated protesting\"",
              "            || FactSanction[Reason] = \"Simulation\"",
              "            || FactSanction[Reason] = \"Spitting\"",
              "            || FactSanction[Reason] = \"Straight red card - dangerous tackle\"",
              "            || FactSanction[Reason] = \"Unsportsmanlike conduct\"",
              "    ),",
              "    VAR LastMatchDate =",
              "        CALCULATE(",
              "            MAX(DimMatch[DateKey]),",
              "            FILTER(",
              "                DimMatch,",
              "                DimMatch[DateKey] <= FactSanction[SanctionDateKey]",
              "                    && (DimMatch[HomeClubKey] = FactSanction[ClubKey]",
              "                        || DimMatch[AwayClubKey] = FactSanction[ClubKey])",
              "            )",
              "        )",
              "    VAR IsHome =",
              "        NOT ISBLANK(LastMatchDate)",
              "        && COUNTROWS(",
              "            FILTER(",
              "                DimMatch,",
              "                DimMatch[DateKey] = LastMatchDate",
              "                    && DimMatch[HomeClubKey] = FactSanction[ClubKey]",
              "            )",
              "        ) > 0",
              "    RETURN IF(IsHome, 1, 0)",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "390983e6-3753-4ad2-af90-2d0d61f4e5dd"
          },
          {
            "name": "Sanctions Extérieur",
            "expression": [
              "",
              "SUMX(",
              "    FILTER(",
              "        FactSanction,",
              "        FactSanction[Reason] = \"Abusive language in mixed zone\"",
              "            || FactSanction[Reason] = \"Accumulation of yellow cards\"",
              "            || FactSanction[Reason] = \"Deliberate elbow strike\"",
              "            || FactSanction[Reason] = \"Inappropriate gesture towards an opponent\"",
              "            || FactSanction[Reason] = \"Insulting the referee\"",
              "            || FactSanction[Reason] = \"On-field brawl\"",
              "            || FactSanction[Reason] = \"Red card - last man foul\"",
              "            || FactSanction[Reason] = \"Repeated protesting\"",
              "            || FactSanction[Reason] = \"Simulation\"",
              "            || FactSanction[Reason] = \"Spitting\"",
              "            || FactSanction[Reason] = \"Straight red card - dangerous tackle\"",
              "            || FactSanction[Reason] = \"Unsportsmanlike conduct\"",
              "    ),",
              "    VAR LastMatchDate =",
              "        CALCULATE(",
              "            MAX(DimMatch[DateKey]),",
              "            FILTER(",
              "                DimMatch,",
              "                DimMatch[DateKey] <= FactSanction[SanctionDateKey]",
              "                    && (DimMatch[HomeClubKey] = FactSanction[ClubKey]",
              "                        || DimMatch[AwayClubKey] = FactSanction[ClubKey])",
              "            )",
              "        )",
              "    VAR IsAway =",
              "        NOT ISBLANK(LastMatchDate)",
              "        && COUNTROWS(",
              "            FILTER(",
              "                DimMatch,",
              "                DimMatch[DateKey] = LastMatchDate",
              "                    && DimMatch[AwayClubKey] = FactSanction[ClubKey]",
              "            )",
              "        ) > 0",
              "    RETURN IF(IsAway, 1, 0)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "494fd6b6-43a6-4529-ae6e-d80f92a9ad62"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FactAttendance",
        "lineageTag": "5e2a6cd3-1bf5-4861-94af-3e0e03f2e4a6",
        "columns": [
          {
            "name": "ClubKey",
            "dataType": "int64",
            "sourceColumn": "ClubKey",
            "formatString": "0",
            "lineageTag": "ee72b532-fe7b-4257-9b43-2d130d32bca5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Matchday",
            "dataType": "int64",
            "sourceColumn": "Matchday",
            "formatString": "0",
            "lineageTag": "b24d7602-99a3-406c-ab10-1e63a7e89153",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateKey",
            "dataType": "string",
            "sourceColumn": "DateKey",
            "lineageTag": "73ee7385-4830-4857-b695-7557df7f661a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MatchKey",
            "dataType": "string",
            "sourceColumn": "MatchKey",
            "lineageTag": "b10c1b8c-6fd9-44c0-8343-802cc37253c8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Opponent",
            "dataType": "string",
            "sourceColumn": "Opponent",
            "lineageTag": "e5d1480e-f783-4644-905b-f103f17341df",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Attendance",
            "dataType": "int64",
            "sourceColumn": "Attendance",
            "formatString": "0",
            "lineageTag": "cbb46ed5-20a2-46ab-bf51-5f58d21aff95",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StadiumCapacity",
            "dataType": "int64",
            "sourceColumn": "StadiumCapacity",
            "formatString": "0",
            "lineageTag": "ac862ac7-2dc9-444d-9f69-c51da4aa29b7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FillRatePct",
            "dataType": "double",
            "sourceColumn": "FillRatePct",
            "lineageTag": "1d33769b-fec7-4d9d-b5b7-86f6f58d0a41",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weather",
            "dataType": "string",
            "sourceColumn": "Weather",
            "lineageTag": "6b489c54-2770-48ba-ac1a-9ac2c0ca32ef",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TemperatureC",
            "dataType": "int64",
            "sourceColumn": "TemperatureC",
            "formatString": "0",
            "lineageTag": "af88d0f3-3c35-4341-b9af-e08ceb2b8ee7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactAttendance",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Staging_StadiumAttendance,",
                "    #\"Requêtes fusionnées\" = Table.NestedJoin(Source, {\"club\"}, DimClub, {\"ClubName\"}, \"DimClub\", JoinKind.LeftOuter),",
                "    #\"DimClub développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées\", \"DimClub\", {\"ClubKey\"}, {\"DimClub.ClubKey\"}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"DimClub développé\",{{\"DimClub.ClubKey\", \"ClubKey\"}}),",
                "    #\"Colonnes permutées\" = Table.ReorderColumns(#\"Colonnes renommées\",{\"ClubKey\", \"club\", \"matchday\", \"date\", \"opponent\", \"attendance\", \"stadium_capacity\", \"fill_rate\", \"weather\", \"temperature_c\"}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Colonnes permutées\",{\"club\"}),",
                "    #\"Requêtes fusionnées1\" = Table.NestedJoin(#\"Colonnes supprimées\", {\"date\"}, DimDate, {\"DateKey\"}, \"DimDate\", JoinKind.LeftOuter),",
                "    #\"DimDate développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées1\", \"DimDate\", {\"DateKey\"}, {\"DimDate.DateKey\"}),",
                "    #\"Colonnes renommées1\" = Table.RenameColumns(#\"DimDate développé\",{{\"DimDate.DateKey\", \"DateKey\"}}),",
                "    #\"Colonnes permutées1\" = Table.ReorderColumns(#\"Colonnes renommées1\",{\"DateKey\", \"ClubKey\", \"matchday\", \"date\", \"opponent\", \"attendance\", \"stadium_capacity\", \"fill_rate\", \"weather\", \"temperature_c\"}),",
                "    #\"Colonnes supprimées1\" = Table.RemoveColumns(#\"Colonnes permutées1\",{\"date\"}),",
                "    #\"Colonnes permutées2\" = Table.ReorderColumns(#\"Colonnes supprimées1\",{\"ClubKey\", \"matchday\", \"DateKey\", \"opponent\", \"attendance\", \"stadium_capacity\", \"fill_rate\", \"weather\", \"temperature_c\"}),",
                "    #\"Colonnes renommées2\" = Table.RenameColumns(#\"Colonnes permutées2\",{{\"matchday\", \"Matchday\"}}),",
                "    #\"Requêtes fusionnées2\" = Table.NestedJoin(#\"Colonnes renommées2\", {\"ClubKey\", \"Matchday\", \"DateKey\"}, DimMatch, {\"HomeClubKey\", \"Matchday\", \"DateKey\"}, \"DimMatch\", JoinKind.LeftOuter),",
                "    #\"DimMatch développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées2\", \"DimMatch\", {\"MatchKey\"}, {\"DimMatch.MatchKey\"}),",
                "    #\"Colonnes renommées3\" = Table.RenameColumns(#\"DimMatch développé\",{{\"DimMatch.MatchKey\", \"MatchKey\"}}),",
                "    #\"Colonnes permutées3\" = Table.ReorderColumns(#\"Colonnes renommées3\",{\"ClubKey\", \"Matchday\", \"DateKey\", \"MatchKey\", \"opponent\", \"attendance\", \"stadium_capacity\", \"fill_rate\", \"weather\", \"temperature_c\"}),",
                "    #\"Colonnes renommées4\" = Table.RenameColumns(#\"Colonnes permutées3\",{{\"opponent\", \"Opponent\"}, {\"attendance\", \"Attendance\"}, {\"stadium_capacity\", \"StadiumCapacity\"}, {\"fill_rate\", \"FillRatePct\"}, {\"weather\", \"Weather\"}, {\"temperature_c\", \"TemperatureC\"}})",
                "in",
                "    #\"Colonnes renommées4\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "RivalryPair",
        "lineageTag": "0512ac49-145f-4a3a-8bc9-182a39d2d29c",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "HomeClubKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DimMatch[HomeClubKey]",
            "formatString": "0",
            "lineageTag": "9c3ced32-39c2-4fa5-9364-68b8ec8c8d91",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "AwayClubKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DimMatch[AwayClubKey]",
            "formatString": "0",
            "lineageTag": "ed368441-97ff-47ae-a8d4-c4234f87cfed",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "PairLabel",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[PairLabel]",
            "lineageTag": "7b1e10cd-e77d-4490-a6be-5ea431c2a5de",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "RivalryPair",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    SUMMARIZE(DimMatch, DimMatch[HomeClubKey], DimMatch[AwayClubKey]),",
                "    \"PairLabel\",",
                "        LOOKUPVALUE(DimClub[ClubName], DimClub[ClubKey], [HomeClubKey])",
                "            & \" – \" & LOOKUPVALUE(DimClub[ClubName], DimClub[ClubKey], [AwayClubKey])",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Goals in Rivalry",
            "expression": [
              "",
              "CALCULATE(SUM(FactClubMatch[GoalsFor]),",
              "    FILTER(DimMatch,",
              "        DimMatch[HomeClubKey] = MAX(RivalryPair[HomeClubKey])",
              "            && DimMatch[AwayClubKey] = MAX(RivalryPair[AwayClubKey])))"
            ],
            "formatString": "0",
            "lineageTag": "e6a3ca88-365f-4112-845e-ac33d1e6b0b0"
          },
          {
            "name": "Avg Attendance in Rivalry",
            "expression": "CALCULATE(AVERAGE(DimMatch[Attendance]), FILTER(DimMatch, DimMatch[HomeClubKey] = MAX(RivalryPair[HomeClubKey]) && DimMatch[AwayClubKey] = MAX(RivalryPair[AwayClubKey])))",
            "lineageTag": "c68d1e31-ab53-43c8-994d-194dda9ef0cb",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Fill Rate in Rivalry",
            "expression": [
              "",
              "VAR HomeK = MAX(RivalryPair[HomeClubKey])",
              "VAR AwayK = MAX(RivalryPair[AwayClubKey])",
              "RETURN",
              "    CALCULATE(",
              "        AVERAGE(FactAttendance[FillRatePct]),",
              "        FILTER(DimMatch,",
              "            DimMatch[HomeClubKey] = HomeK && DimMatch[AwayClubKey] = AwayK),",
              "        REMOVEFILTERS(DimClub)",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "236fbccd-a455-4729-89da-0c9102f8477b"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a3416360a676479db6da3423622b5c32"
          }
        ]
      },
      {
        "name": "stadium_attendance",
        "lineageTag": "ae8d5c3e-64c7-4869-9f5d-25511e42e5fa",
        "columns": [
          {
            "name": "club",
            "dataType": "string",
            "sourceColumn": "club",
            "lineageTag": "6052f550-52b5-48dd-aefc-cf765ce9a24a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "matchday",
            "dataType": "int64",
            "sourceColumn": "matchday",
            "formatString": "0",
            "lineageTag": "369d1a85-085a-4bd7-a0aa-64287821fd61",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date",
            "dataType": "string",
            "sourceColumn": "date",
            "lineageTag": "46426b89-0e31-4a68-b307-132f03460d17",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "opponent",
            "dataType": "string",
            "sourceColumn": "opponent",
            "lineageTag": "5cf1c4ab-cfad-46d9-88a3-afb14f922f77",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "attendance",
            "dataType": "int64",
            "sourceColumn": "attendance",
            "formatString": "0",
            "lineageTag": "24a4e86e-6220-49a2-b937-f8ee84775f3c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "stadium_capacity",
            "dataType": "int64",
            "sourceColumn": "stadium_capacity",
            "formatString": "0",
            "lineageTag": "d1bf5f87-ded3-4bf3-bf6a-7771089263eb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "fill_rate",
            "dataType": "int64",
            "sourceColumn": "fill_rate",
            "formatString": "0",
            "lineageTag": "6120b243-0167-4d91-a54b-e01145b4194d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "weather",
            "dataType": "string",
            "sourceColumn": "weather",
            "lineageTag": "946b4936-119e-4e0f-a2c7-120e800b4322",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "temperature_c",
            "dataType": "int64",
            "sourceColumn": "temperature_c",
            "formatString": "0",
            "lineageTag": "eace014f-8131-4d43-892c-1425eab19b27",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "stadium_attendance",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\frede\\Downloads\\stadium_attendance.csv\"),[Delimiter=\";\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"club\", type text}, {\"matchday\", Int64.Type}, {\"date\", type text}, {\"opponent\", type text}, {\"attendance\", Int64.Type}, {\"stadium_capacity\", Int64.Type}, {\"fill_rate\", Int64.Type}, {\"weather\", type text}, {\"temperature_c\", Int64.Type}})",
                "in",
                "    #\"Type modifié\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "stadium_attendance (2)",
        "lineageTag": "8c1061e5-2978-42e4-89c8-b476d9dd69dd",
        "columns": [
          {
            "name": "club",
            "dataType": "string",
            "sourceColumn": "club",
            "lineageTag": "a956883e-5c7c-40e9-a79e-2f460bdaf2ad",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "matchday",
            "dataType": "int64",
            "sourceColumn": "matchday",
            "formatString": "0",
            "lineageTag": "d0b97683-5ebf-41db-8339-8c86f6f500f0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date",
            "dataType": "string",
            "sourceColumn": "date",
            "lineageTag": "70bf760e-a037-43d8-b90c-5c880f648d4c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "opponent",
            "dataType": "string",
            "sourceColumn": "opponent",
            "lineageTag": "5550176b-4d62-4095-850c-4973cb8c6ca5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "attendance",
            "dataType": "int64",
            "sourceColumn": "attendance",
            "formatString": "0",
            "lineageTag": "125157e2-94b5-49d0-8f80-44ce84af972a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "stadium_capacity",
            "dataType": "int64",
            "sourceColumn": "stadium_capacity",
            "formatString": "0",
            "lineageTag": "9876183c-4153-49a5-8361-45fdf7b08514",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "fill_rate",
            "dataType": "int64",
            "sourceColumn": "fill_rate",
            "formatString": "0",
            "lineageTag": "53c8a5b9-f1f3-427e-a0eb-1739c0b39a63",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "weather",
            "dataType": "string",
            "sourceColumn": "weather",
            "lineageTag": "7e7ce871-ff15-4368-8f2f-432006d5b422",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "temperature_c",
            "dataType": "int64",
            "sourceColumn": "temperature_c",
            "formatString": "0",
            "lineageTag": "8b9c2b29-f779-4c1c-996a-8acaf35747c0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Fill_Rate_Pct",
            "dataType": "double",
            "sourceColumn": "Fill_Rate_Pct",
            "lineageTag": "66a9aaac-d4ad-4828-8da8-aa40fc5979af",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "stadium_attendance (2)",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\frede\\Downloads\\stadium_attendance.csv\"),[Delimiter=\";\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"club\", type text}, {\"matchday\", Int64.Type}, {\"date\", type text}, {\"opponent\", type text}, {\"attendance\", Int64.Type}, {\"stadium_capacity\", Int64.Type}, {\"fill_rate\", Int64.Type}, {\"weather\", type text}, {\"temperature_c\", Int64.Type}}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Type modifié\", \"Fill_Rate_Pct\", each Number.FromText(Text.Replace(Text.Trim(Text.From([fill_rate])), \",\", \".\"))),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Personnalisée ajoutée\",{\"Fill_Rate_Pct\"}),",
                "    #\"Personnalisée ajoutée1\" = Table.AddColumn(#\"Colonnes supprimées\", \"Personnalisé\", each if [fill_rate] > 100 then [fill_rate] / 10 else [fill_rate]),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Personnalisée ajoutée1\",{{\"Personnalisé\", type number}}),",
                "    #\"Colonnes renommées\" = Table.RenameColumns(#\"Type modifié1\",{{\"Personnalisé\", \"Fill_Rate_Pct\"}})",
                "in",
                "    #\"Colonnes renommées\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "StandingsFinal",
        "lineageTag": "aecdc510-652e-4be4-9ec9-4365bf404c98",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "ClubKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DimClub[ClubKey]",
            "formatString": "0",
            "lineageTag": "94dfbb6d-4fbe-4f68-a315-dbd8efa1c227",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "@FinalPoints",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[@FinalPoints]",
            "formatString": "0",
            "lineageTag": "151eb27b-d24b-4378-997a-ae9d9a0551a8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "FinalRank",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[FinalRank]",
            "formatString": "0",
            "lineageTag": "85e34f89-7e7e-4da2-a315-84b35e1ba5e8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "StandingsFinal",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR ClubsWithPoints = ",
                "    ADDCOLUMNS(",
                "        ALL(DimClub[ClubKey]),",
                "        \"@FinalPoints\",",
                "        CALCULATE(",
                "            SUM(FactClubMatch[Points]),",
                "            DimMatch[Matchday] = 38",
                "        )",
                "    )",
                "RETURN",
                "    ADDCOLUMNS(",
                "        ClubsWithPoints,",
                "        \"FinalRank\",",
                "        RANKX(ClubsWithPoints, [@FinalPoints], [@FinalPoints], DESC, Dense)",
                "    )"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "54b940bbd7174e0582982298f3716753"
          }
        ]
      },
      {
        "name": "MinutesBins",
        "lineageTag": "4ce38a47-b3fd-4e40-b9ed-b422bc3b40a1",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Bin Sort",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Bin Sort]",
            "formatString": "0",
            "lineageTag": "e1e3a0af-2978-4566-b118-d9fc52cce527",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Bin Label",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Bin Label]",
            "lineageTag": "588f348c-cdb0-4d4f-8bc0-1449ba76cab9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "MinutesBins",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "DATATABLE(",
                "    \"Bin Sort\", INTEGER,",
                "    \"Bin Label\", STRING,",
                "    {",
                "        {1, \"0-500\"},",
                "        {2, \"500-1K\"},",
                "        {3, \"1K-1.5K\"},",
                "        {4, \"1.5K-2K\"},",
                "        {5, \"2K-2.5K\"},",
                "        {6, \"2.5K-3K\"},",
                "        {7, \"3K+\"}",
                "    }",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "46a0cdbe5cc5420b9099430d0bea46ff"
          }
        ]
      },
      {
        "name": "FillRate Bins",
        "lineageTag": "6fde2fb4-cfdf-4010-af9e-37b884e24e8e",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0",
            "lineageTag": "cdd04b87-4909-4610-9261-86c93f8fa223",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Min",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Min]",
            "formatString": "0",
            "lineageTag": "32d0d9c3-7a5a-4a41-8d4a-f572493a6ac3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Max",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Max]",
            "formatString": "0",
            "lineageTag": "fcea7a47-d6d2-478a-9f39-dd45469ffda8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Label",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Label]",
            "lineageTag": "09c703a2-d94f-47fa-88b6-9630dcbe0665",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Sort",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Sort]",
            "formatString": "0",
            "lineageTag": "54281ed8-7193-4437-a127-06b186d62004",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FillRate Bins",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR Step = 5",
                "RETURN",
                "ADDCOLUMNS (",
                "    GENERATESERIES ( 0, 100, Step ),",
                "    \"Min\", [Value],",
                "    \"Max\", [Value] + Step,",
                "    \"Label\", FORMAT ( [Value], \"0\" ) & \"% – \" & FORMAT ( [Value] + Step, \"0\" ) & \"%\",",
                "    \"Sort\", [Value]",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sanctions by FillRate Bin",
            "expression": [
              "",
              "VAR MinBin = SELECTEDVALUE ( 'FillRate Bins'[Min] )",
              "VAR MaxBin = SELECTEDVALUE ( 'FillRate Bins'[Max] )",
              "VAR AttendanceInBin =",
              "    FILTER (",
              "        ALL ( FactAttendance ),",
              "        FactAttendance[FillRatePct] >= MinBin",
              "            && FactAttendance[FillRatePct] < MaxBin",
              "    )",
              "VAR Keys =",
              "    SELECTCOLUMNS (",
              "        AttendanceInBin,",
              "        \"ClubKey\", FactAttendance[ClubKey],",
              "        \"SanctionDateKey\", FactAttendance[DateKey]",
              "    )",
              "RETURN",
              "    CALCULATE (",
              "        COUNTROWS ( FactSanction ),",
              "        TREATAS ( Keys, FactSanction[ClubKey], FactSanction[SanctionDateKey] )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "704ea6d0-1d2b-4a50-8288-d13dcbd06d1f"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a9c351d607a14fd5a4e86a7caa6a1427"
          }
        ]
      },
      {
        "name": "KPIs Player",
        "lineageTag": "b65b825a-92e1-458b-859d-3331a559aa8a",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Column",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Column]",
            "formatString": "0",
            "lineageTag": "746e6427-e68b-425b-9641-d6354d5fdec1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "KPIs Player",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Row(\"Column\", BLANK())"
            }
          }
        ],
        "measures": [
          {
            "name": "Goals KPI HTML",
            "expression": [
              "",
              "VAR vPlayer = SUM(FactPlayerSeason[Goals])",
              "VAR vAvg = CALCULATE(AVERAGE(FactPlayerSeason[Goals]), ALLEXCEPT(DimPlayer, DimPlayer[Position]))",
              "VAR vMin = CALCULATE(MIN(FactPlayerSeason[Goals]), ALLEXCEPT(DimPlayer, DimPlayer[Position]))",
              "VAR vMax = CALCULATE(MAX(FactPlayerSeason[Goals]), ALLEXCEPT(DimPlayer, DimPlayer[Position]))",
              "",
              "VAR vPlayerFmt = IF(ISBLANK(vPlayer) || vPlayer = 0, \"0\", FORMAT(vPlayer, \"#,0\"))",
              "VAR vAvgFmt = IF(ISBLANK(vAvg), \"–\", FORMAT(vAvg, \"#,0\"))",
              "VAR vMinFmt = IF(ISBLANK(vMin), \"–\", FORMAT(vMin, \"#,0\"))",
              "VAR vMaxFmt = IF(ISBLANK(vMax), \"–\", FORMAT(vMax, \"#,0\"))",
              "",
              "VAR vRange = vMax - vMin",
              "VAR vAvgPct = IF(vRange <= 0, 0.5, DIVIDE(vAvg - vMin, vRange, 0.5))",
              "VAR vAvgX = ROUND(12 + 176 * vAvgPct, 0)",
              "",
              "RETURN",
              "\"",
              "<style>",
              "  * { box-sizing: border-box; }",
              "  .gauge-goals { font-family: 'Segoe UI', sans-serif; background: #fff; padding: 14px; border-radius: 10px; text-align: center; width: 200px; }",
              "  .gauge-goals .gauge-icon { font-size: 22px; margin-bottom: 2px; display: block; }",
              "  .gauge-goals .gauge-label { font-size: 11px; color: #444; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; display: block; }",
              "  .gauge-goals .gauge-svg-wrap { display: block; width: 200px; height: 70px; margin: 0 auto 8px auto; }",
              "  .gauge-goals .gauge-scale-row { display: flex; justify-content: space-between; width: 200px; margin: 0 auto 10px auto; font-size: 11px; color: #666; font-weight: 600; }",
              "  .gauge-goals .gauge-value { font-size: 32px; font-weight: 700; color: #1a1a1a; display: block; margin-bottom: 4px; }",
              "  .gauge-goals .gauge-moy { font-size: 11px; color: #666; }",
              "</style>",
              "<div class='gauge-goals'>",
              "  <span class='gauge-icon'>⚽</span>",
              "  <span class='gauge-label'>Buts</span>",
              "  <span class='gauge-svg-wrap'>",
              "    <svg viewBox='0 0 200 110' width='200' height='70' preserveAspectRatio='xMidYMid meet'>",
              "      <path d='M 12 88 A 88 88 0 0 0 188 88' fill='none' stroke='#1565C0' stroke-width='12' stroke-linecap='round'/>",
              "      <line x1='\" & vAvgX & \"' y1='88' x2='\" & vAvgX & \"' y2='70' stroke='#0D47A1' stroke-width='2.5' stroke-linecap='round'/>",
              "    </svg>",
              "  </span>",
              "  <div class='gauge-scale-row'><span>\" & vMinFmt & \"</span><span>\" & vMaxFmt & \"</span></div>",
              "  <span class='gauge-value'>\" & vPlayerFmt & \"</span>",
              "  <span class='gauge-moy'>Moy. poste \" & vAvgFmt & \"</span>",
              "</div>",
              "\""
            ],
            "lineageTag": "74a018e3-d99f-4536-a033-83dde721a1e0"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3bdf204a3e7e4f7d95b8b390a3a2ce0d"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ]
      },
      {
        "name": "club_logos",
        "lineageTag": "2e387e03-129b-439a-8677-623abd4b5a29",
        "columns": [
          {
            "name": "club_name",
            "dataType": "string",
            "sourceColumn": "club_name",
            "lineageTag": "f97a1446-950d-496a-a674-ea49357d7e78",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "logo_url",
            "dataType": "string",
            "sourceColumn": "logo_url",
            "lineageTag": "ca078cc1-eed1-40d6-8ac9-17f7726e820e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "club_logos",
            "mode": "import",
            "queryGroup": "Staging Queries",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Json.Document(File.Contents(\"C:\\Users\\frede\\Downloads\\club_logos.json\")),",
                "    #\"Converti en table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Column1 développé\" = Table.ExpandRecordColumn(#\"Converti en table\", \"Column1\", {\"club_name\", \"logo_url\"}, {\"club_name\", \"logo_url\"}),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Column1 développé\",{{\"club_name\", type text}, {\"logo_url\", type text}})",
                "in",
                "    #\"Type modifié\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "beaeec36-39bd-4931-bbf5-5e6bfb347081",
        "fromTable": "Staging_MatchResults",
        "fromColumn": "match_date",
        "toTable": "LocalDateTable_776675fc-bef2-45d4-a7a0-3b6198fcefb6",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "f8fb8e4a-f9c2-47e6-b542-ac19e0ae60d1",
        "fromTable": "Staging_Transfers",
        "fromColumn": "transfer_date",
        "toTable": "LocalDateTable_8fae75e9-dacc-454d-97aa-fd32e596e033",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "62954abf-f0a2-47cb-aefa-1529da878527",
        "fromTable": "Staging_Sanctions",
        "fromColumn": "sanction_date",
        "toTable": "LocalDateTable_0e28b9c3-ae72-4210-a25c-a7fc4c99d2c6",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "b8d13e74-960e-4026-a359-c0a24664741d",
        "fromTable": "DimDate",
        "fromColumn": "Date",
        "toTable": "LocalDateTable_ff75e868-f378-4c68-a7cc-2d390b38a635",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "dc930c6b-4d5b-43c8-8b11-db68b92a1fcd",
        "fromTable": "Staging_Players",
        "fromColumn": "date_of_birth",
        "toTable": "LocalDateTable_9212df2f-31f2-4d4f-99e0-d419183edf8d",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "d136ba81-6080-4432-924c-af11b4e260c8",
        "fromTable": "Staging_Players",
        "fromColumn": "club_arrival_date",
        "toTable": "LocalDateTable_a1fae906-93c6-48ae-8a23-4173ec467089",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "e78ddb87-cab5-4ab5-a6fc-ce671cf8ebf4",
        "fromTable": "DimPlayer",
        "fromColumn": "DateOfBirth",
        "toTable": "LocalDateTable_1ddaff7e-1747-4fb5-943c-4d38455cfbb1",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "7a8e5622-81d3-4216-862d-f6a915c4d8b3",
        "fromTable": "Staging_Field_Players",
        "fromColumn": "date_of_birth",
        "toTable": "LocalDateTable_e2962b62-a583-45df-b831-8426c7093111",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "cbfe5764-4b1c-4088-8926-48272ff2148c",
        "fromTable": "Staging_Field_Players",
        "fromColumn": "club_arrival_date",
        "toTable": "LocalDateTable_d5744ca4-8cac-40a1-a228-c2696a0c6c9e",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "AutoDetected_f25f4893-960c-465f-8e22-e601c54c64d9",
        "fromTable": "FactClubMatch",
        "fromColumn": "ClubKey",
        "toTable": "DimClub",
        "toColumn": "ClubKey"
      },
      {
        "name": "AutoDetected_4da1b5f0-1ca9-4962-bd68-aaa428925ffd",
        "fromTable": "FactPlayerSeason",
        "fromColumn": "ClubKey",
        "toTable": "DimClub",
        "toColumn": "ClubKey"
      },
      {
        "name": "AutoDetected_33d17c1d-1461-4db6-9e75-3e7e2a84038b",
        "fromTable": "FactSanction",
        "fromColumn": "ClubKey",
        "toTable": "DimClub",
        "toColumn": "ClubKey"
      },
      {
        "name": "AutoDetected_8f70c46a-bdef-4db9-978b-7c6686c7caa0",
        "fromTable": "FactAttendance",
        "fromColumn": "ClubKey",
        "toTable": "DimClub",
        "toColumn": "ClubKey"
      },
      {
        "name": "0805ebb4-22b0-2fd8-a43f-7ebeca51b8e5",
        "fromTable": "FactAttendance",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "fc99d5ef-1ced-30f7-0153-7dd03b3a846b",
        "fromTable": "FactAttendance",
        "fromColumn": "MatchKey",
        "toTable": "DimMatch",
        "toColumn": "MatchKey"
      },
      {
        "name": "e3ab5ef9-bd34-573d-92f6-1d71d6cbdbed",
        "fromTable": "FactClubMatch",
        "fromColumn": "MatchKey",
        "toTable": "DimMatch",
        "toColumn": "MatchKey"
      },
      {
        "name": "f79b0ddf-d80d-89a0-2676-241e9539e906",
        "fromCardinality": "one",
        "fromTable": "FactPlayerSeason",
        "fromColumn": "PlayerKey",
        "toTable": "DimPlayer",
        "toColumn": "PlayerKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "8e624213-826f-134d-5078-f8280a006ee4",
        "fromTable": "FactSanction",
        "fromColumn": "SanctionDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "ce17b6a7-47d2-b838-d97b-acb037538923",
        "fromTable": "FactTransfer",
        "fromColumn": "ArrivalClubKey",
        "toTable": "DimClub",
        "toColumn": "ClubKey"
      },
      {
        "name": "3f4c2061-a05c-d745-88ff-d5fff6eff8f0",
        "fromTable": "FactTransfer",
        "fromColumn": "DepartureClubKey",
        "toTable": "DimClub",
        "toColumn": "ClubKey",
        "isActive": false
      },
      {
        "name": "61d243de-9aeb-3243-486e-f038624bd3fb",
        "fromTable": "FactTransfer",
        "fromColumn": "PlayerKey",
        "toTable": "DimPlayer",
        "toColumn": "PlayerKey",
        "isActive": false,
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "ddbaf5e8-0a45-ef2a-1d14-230822989d78",
        "fromTable": "FactTransfer",
        "fromColumn": "TransferDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "AutoDetected_c9f48139-60c7-40be-aa75-8d30ae3f197e",
        "fromTable": "DimMatch",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "AutoDetected_3b9bdaa5-93cf-4ba2-8e6c-cda44bf4a9c5",
        "fromTable": "stadium_attendance",
        "fromColumn": "club",
        "toTable": "DimClub",
        "toColumn": "ClubName"
      },
      {
        "name": "AutoDetected_df3ac74d-ed92-4bcc-a277-d73ae05bdf15",
        "fromTable": "stadium_attendance (2)",
        "fromColumn": "club",
        "toTable": "DimClub",
        "toColumn": "ClubName"
      },
      {
        "name": "AutoDetected_b14dfed9-fe34-462f-87cf-c1c15625e9e2",
        "fromCardinality": "one",
        "fromTable": "club_logos",
        "fromColumn": "club_name",
        "toTable": "DimClub",
        "toColumn": "ClubName",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "AutoDetected_05820255-0746-4a18-a168-df31113c8218",
        "fromCardinality": "one",
        "fromTable": "club_logos",
        "fromColumn": "club_name",
        "toTable": "Staging_Clubs",
        "toColumn": "club_name",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "cultures": [
      {
        "name": "fr-FR",
        "linguisticMetadata": {}
      }
    ],
    "queryGroups": [
      {
        "folder": "Staging Queries",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Dimensions",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ]
      },
      {
        "folder": "Facts",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Staging_MatchResults\",\"Staging_PlayerStats\",\"Staging_Transfers\",\"Staging_StadiumAttendance\",\"Staging_Sanctions\",\"Staging_Clubs\",\"Staging_Players\",\"DimClub\",\"DimPlayer\",\"DimDate\",\"DimMatch\",\"Staging_Field_Players\",\"FactClubMatch\",\"FactPlayerSeason\",\"FactTransfer\",\"FactSanction\",\"FactAttendance\",\"stadium_attendance\",\"stadium_attendance (2)\",\"club_logos\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"SortArrays\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ]
  }
}